### ISSUE TITLE
Add Aeon labs Micro module Double switch G2 to database

### ISSUE THREAD

**Issue by pierok13** [cdjackson/HABmin#106]
hello,
first of all :+1: great work ! i wish i could have more time to help contribute....
is it possible to add the Aeon labs Micro module Double switch G2 to database. it is the same as the mses (http://www.pepper1.net/zwavedb/device/42)
reference: [id:11,type:3]
thanks for everything
Pierre

**Comment by cdjackson** [comment]
Very old ZWave issue - update database if not resolved.
