### ISSUE TITLE
Z-Wave Binding View in HABmin Causes High CPU Load on Underpowered Devices

### ISSUE THREAD

**Issue by NolanGarrett** [cdjackson/HABmin#124]
There may not be a resolution for this, however, we have found that on devices like the RPi, selecting the Z-Wave binding for configuration launches a series of javascripts that pushes the RPi to 100% CPU for a minute or even a few minutes. Larger networks experience this problem more acutely.

**Comment by cdjackson** [comment]
This will be looked at in OH2/HABmin2 but no further changes on this will be done for HABmin1.
