### ISSUE TITLE
View state of Z-Wave network heals

### ISSUE THREAD

**Issue by NolanGarrett** [cdjackson/HABmin#126]
When the current heal process runs, it's difficult to know that it is running or what it is doing. While it's possible to expand the node, then go to the status node and expand this, you basically have to track down what is occurring on a per-node basis.

If you have 40 nodes, for example, you potentially need to click 80 times to find out which node is being healed and what the state of that node is.

**Comment by cdjackson** [comment]
This is included in habmin 2.
