### ISSUE TITLE
Charts - Axis Configuration - Format returns %.1f

### ISSUE THREAD

**Issue by IvarV** [cdjackson/HABmin#139]
In the editor "Axis Configuration", if I select "Format" say.. "Float (0.0)" the x axis doesn't show the value, rather "%.1f" 
The value shows up correctly if I don't select anything in the format field. 

Attached screen shot. 
![bug_format](https://cloud.githubusercontent.com/assets/7561630/2949097/a1d927c0-da0a-11e3-9f69-50e54dc73333.PNG)

**Comment by cdjackson** [comment]
HABmin2 allows control over this.
