### ISSUE TITLE
Habmin tries to get the association groups of Greenwave devices, but they do not support that.

### ISSUE THREAD

**Issue by GertKonemann** [cdjackson/HABmin#146]
When habmin tries to heal a device, it also tries to heal the Greenwave powernodes. This results in errors, as the Greenwave devices do not support association groups.

Gert

![image](https://cloud.githubusercontent.com/assets/2301236/3208777/c41d6c26-ee44-11e3-894f-c784963f5091.png)

**Comment by cdjackson** [comment]
This issue should be resolved as we now request associations differently.

**Comment by GertKonemann** [comment]
This is solved indeed. 

Gert
