### ISSUE TITLE
Variable date range for graphs

### ISSUE THREAD

**Issue by mdbergmann** [cdjackson/HABmin#151]
I'd like to create a graph with data from a certain date to a certain date. That means the period can have variable from and to dates, where at the moment the to date is fixed to "now".
How the dates are entered I don't care that much. This may be a calendar widget or just a text field where the date is entered.
I think this doesn't necessarily need to be possible for stored graphs but more for graphs in the Item list.

Manfred

**Comment by cdjackson** [comment]
Will not be implemented in OH1
