### ISSUE TITLE
Add products.xml extension - not compiled into binding

### ISSUE THREAD

**Issue by NolanGarrett** [cdjackson/HABmin#159]
I think it would be useful / helpful to add an 'extension' to products.xml that allows an end user to edit an "additional products" file in the configuration directory to add products on the fly, instead of needing to update the binding and recompile it.

**Comment by cdjackson** [comment]
This is not planned.  I prefer to keep the database under configuration control an embedded in the binding. Errors in the database can be problematic both for the binding operation and the devices.
