### ISSUE TITLE
Z-Wave NodeAdvancer stuck in infinite loop

### ISSUE THREAD

**Issue by holgerfriedrich** [cdjackson/HABmin#189]
Dear Chris,
thanks a lot for putting the efforts in the new NodeAdvancer. It helped a lot and works fine most of the time.

I have one issue which showed up a few times (AFAIK when starting the binding). One node is stuck in an endless loop which causes a *lot* of messages to be sent out to this node (I saw a node which had received 20000 messages). The only thing which helped was to restart openhab.
It happened to two different FGRM222 deviced which worked fine before.

Log snippet
http://www.jrl.cs.uni-frankfurt.de/download/zwave-2014-48.short.log.gz

Habmin 1.6.0 (master.zip dated Nov26, 9:40am) / Openhab 1.6.0 release
Not yet seen on latest master, but it did not happen too often before so I cannot tell if it is affected.

**Comment by cdjackson** [comment]
The node advancer has now completely changed in 1.7. I'll close this - if the problem still exists please raise a further issue.
