### ISSUE TITLE
HABmin offline

### ISSUE THREAD

**Issue by damylen** [cdjackson/HABmin#194]
Hi,

As far as I can see I followed the installation instructions correctly. But i'm probably missed something, because habmin remains offline. I'm running openhab (1.6.1) and using the latest release from HABmin. 

When I go to the habmin url, i see the pages, but won't load any data. openhab is running. Looking at the console I get the following 404 errors: 

http://192.168.1.108:8080/services/habmin/config/rules/model/list?_dc=1419388556483 404 (ProxyServlet: /services/habmin/config/rules/model/list)

What am I doing wrong here?

Arnoud

**Comment by snizzleorg** [comment]
I have the same problem. 

```
org.openhab.io.habmin-1.7.0-SNAPSHOT.jar
org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar
```

and neither habmin nor habmin2 are working. The web interface shows but all the pages remain empty. Is there any kind of log file I can check?

**Comment by cdjackson** [comment]
I don't think that this is a problem with HABmin - if the general web interfaces aren't working (ie HABmin, as reported) then the problem must be somewhere in the openhab core. You can always look in the openhab logfile to see if there's something showing there I guess.

**Comment by snizzleorg** [comment]
Ok. I installed the release version of openhab and the 1.5 habmin binding and now its working again

**Comment by cdjackson** [comment]
Since HABmin is working I'll close this - if you still have problems with HABmin 2 then please open an issue there...
