### ISSUE TITLE
2015-01-04 08:08:03.428 ERROR o.o.b.z.i.c.ZWaveProductDatabase[:114]- Unable to load ZWave product file: 'fibaro/fgs211.xml'

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin#199]
Hello,

I've downloaded latest habmin build and now I'm getting:

2015-01-04 08:08:03.428 ERROR o.o.b.z.i.c.ZWaveProductDatabase[:114]- Unable to load ZWave product file: 'fibaro/fgs211.xml'

errors in zwave openhab log. Can you take a look?

Regards

**Comment by cdjackson** [comment]
Which version are you using? The one on the HABmin site?  It looks like there's something strange happened with some merges...

**Comment by cdjackson** [comment]
Ok - this will be fixed in the HABmin version some time today. I'm just getting someone to test some thermostat class fixes before I load this onto Github.

**Comment by grzech1983** [comment]
Ok. Additiona question: does habmin2 should work correctly with habmin 
addons installed to OH1?

W dniu 2015-01-04 o 12:03, Chris Jackson pisze:
>
> Ok - this will be fixed in the HABmin version some time today. I'm 
> just getting someone to test some thermostat class fixes before I load 
> this onto Github.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cdjackson/HABmin/issues/199#issuecomment-68629007>.
>

-- 

*
*

*Webio *Grzegorz Wołoszyn
ul. Gwiaździsta 8/52
66-400 Gorzów Wlkp.

URL: http://www.webio.pl/
tel. 95 7117188
E-mail: g.woloszyn@webio.pl <mailto:g.woloszyn@webio.pl>

NIP: 599-26-88-099, EU VAT: PL5992688099, REGON: 080265578

Treść tej wiadomości jest poufna i może zawierać materiały przeznaczone 
tylko dla adresata. Jeśli czytelnik tej wiadomości nie jest jej 
zamierzonym adresatem, pracownikiem lub pośrednikiem upoważnionym do jej 
przekazania adresatowi, ostrzegamy, iż publikowanie, dystrybucja lub 
kopiowanie tej wiadomości jest surowo zabronione. Jeśli otrzymałeś tę 
wiadomość omyłkowo, proszę bezzwłocznie zawiadomić o tym nadawcę pocztą 
elektroniczną i skasowanie wiadomości. Dziękujemy za zachowanie zasad 
poufności Webio Grzegorz Wołoszyn.

**Comment by cdjackson** [comment]
Yes, as a general rule - but it doesn’t support everything.  So, it doesn’t support configuring items or sitemaps for example since this (I assume!) will change in OH2.

One other point - I’m aware there’s a bug in the zwave configuration screen if you try and set a config parameter. t won’t cause any problem, but it also doesn’t work at least some of the time and I need to fix this.

Basically, I’m developing it using OH1 at the moment (but will look to support OH2 very soon).

**Comment by grzech1983** [comment]
Hello,

have this issue has been fixed somewhere?

**Comment by cdjackson** [comment]
I've not uploaded it yet as I've been travelling for the past 2 days. I'll be home tonight and will upload it then.

**Comment by cdjackson** [comment]
I’ve just uploaded a new version that should fix this.

**Comment by grzech1983** [comment]
Great. Thanks
