### ISSUE TITLE
[zwave] missing devices in HABmin's zwave view

### ISSUE THREAD

**Issue by petrklus** [cdjackson/HABmin#202]
Hello!

I am not seeing all of my device details in the Devices view:

![image](https://cloud.githubusercontent.com/assets/1115667/5689881/d4c423d2-986f-11e4-847e-2c006eee9f83.png)

The missing devices are battery powered (motion sensors etc), however, I did allow enough time for them to "call home" and they do work - I am using the motion sensors in rules that work well.

I've recently upgraded to 1.6.1, only transferring configurations - no other directory was carried over to ensure that I've started "from scratch". However, the Devices view was almost exactly the same on 1.5.0 from which I've upgraded as well.

I am running zwave + habmin package versioned 1.7.0, from this repository.

**Comment by cdjackson** [comment]
Its hard to say without seeing the logs but the device can only initialise when it receives a wakeup notification.  So even if it's sending alerts this doesn't mean the binding is able to talk to the device.

Do you know what the wakeup period is set to?

I would manually wake the devices to see if this helps. The katest version of the binding will set the wakeup during initialization if needed.  If it doesn't work please send a log. 

Chris



Sent from Samsung Mobile

**Comment by petrklus** [comment]
Some of the devices have wake up period of one hour and some two - either
way there was plenty of time for that to occur!

I will try the following (correct me please if I am wrong):
- go to the motion sensors and click the button
- if that does not help, run in zwave in debug mode and post logs

Best,

Petr

**Comment by cdjackson** [comment]
Thanks - that sounds fine.

**Comment by petrklus** [comment]
Ok, just done it - did not seem to help. Enabled TRACE logging for zwave, here is the out:

https://gist.github.com/petrklus/9f39d053c0d356be0f27

Towards the end I've also pressed the motion sensor's button (and it worked as it turned blue as it should).

Let me know what you think please and have a great Saturday!

**Comment by petrklus** [comment]
I think that the trouble is here:
```
11:59:28.188 DEBUG o.o.b.z.i.ZWaveActiveBinding[:431]- ZwaveIncomingEvent
11:59:28.188 DEBUG o.o.b.z.i.ZWaveActiveBinding[:453]- NODE 6: Got a value event from Z-Wave network, endpoint = 0, command class = SENSOR_MULTILEVEL, value = 1496
11:59:28.189 TRACE o.o.b.z.i.c.ZWaveConverterHandler[:284]- Getting converter for item = ZWave_Motion_IND_Bathroom01_Tamper, command class = SENSOR_MULTILEVEL, item command class = sensor_alarm
11:59:28.189 TRACE o.o.b.z.i.c.ZWaveConverterHandler[:284]- Getting converter for item = ZWave_Motion_IND_Bathroom01, command class = SENSOR_MULTILEVEL, item command class = sensor_binary
11:59:28.189 TRACE o.o.b.z.i.c.ZWaveConverterHandler[:284]- Getting converter for item = ZWave_Motion_IND_Bathroom01_Battery, command class = SENSOR_MULTILEVEL, item command class = battery
11:59:28.189 TRACE o.o.b.z.i.c.ZWaveConverterHandler[:284]- Getting converter for item = ZWave_Motion_IND_Bathroom01_Temperature, command class = SENSOR_MULTILEVEL, item command class = sensor_multilevel
11:59:28.190 TRACE o.o.b.z.i.c.ZWaveConverterHandler[:284]- Getting converter for item = ZWave_Motion_IND_Bathroom01_LightLevel, command class = SENSOR_MULTILEVEL, item command class = sensor_multilevel
11:59:28.190 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.ZWaveNetworkMonitor@1167767
11:59:28.190 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.config.ZWaveConfiguration@176bdf3
11:59:28.191 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeStageAdvancer@1a3a121
11:59:28.191 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveWakeUpCommandClass@1a7b8d6
11:59:28.191 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeStageAdvancer@582906
11:59:28.192 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeStageAdvancer@1ed69ea
11:59:28.192 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeStageAdvancer@1c4b0cc
11:59:28.192 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeStageAdvancer@3341c9
11:59:28.192 TRACE o.o.b.z.i.p.ZWaveController[:511]- Notifying org.openhab.binding.zwave.internal.protocol.initialization.ZWaveNodeStageAdvancer@9e3c6
11:59:28.192 DEBUG o.o.b.z.i.p.s.ApplicationCommandMessageClass[:85]- Transaction not completed: node address inconsistent.
```

**Comment by cdjackson** [comment]
> 
> I think that the trouble is here:
> 
Why?

**Comment by petrklus** [comment]
It's exactly when I press the button - and it does not seem to complete:

```11:59:28.192 DEBUG o.o.b.z.i.p.s.ApplicationCommandMessageClass[:85]- Transaction not completed: node address inconsistent.```

But I can be completely wrong of course!

**Comment by cdjackson** [comment]
Yes, so this message (i.e. when you press the button) might not be working (that’s the problem of course), but this message is completely normal. This is just saying that a transaction didn’t complete, but in this case there is no transaction since the message was initiated from the device (transactions are only initiated from the controller so will only be completed when a response is received to a controller request).

I’ll try and take a look at the log later.=

**Comment by petrklus** [comment]
Oh, makes sense! Thanks a lot, I should be around almost the whole weekend to try out stuff.

**Comment by cdjackson** [comment]
Hi Petr,
I just had a quick look at your log and there are no wakeups in there for the 4 devices you mention. Until a wakeup is received it won't do anything. Can you maybe send me the log when it's woken up?

I might add a "last wakeup" to the status information to make this easier to see...

Chris

**Comment by petrklus** [comment]
.. I thought that a triple tap on the device's button would force a wakeup,
is that not correct?

I will wait then for a few hours to see what is going on. If I do not see
the wake up by the evening, I will have a look with ozwcp to see what I can
find.

Thanks!

**Comment by cdjackson** [comment]
A triple click should normally wake the device, but if I do a search in your log for 'node is awake' I don't see anything. I see some information from node 6 and 10, but it's only sensor data being sent - it hasn't sent a wakeup or a NIF.

![screen shot 2015-01-10 at 12 38 40](https://cloud.githubusercontent.com/assets/1041475/5691574/f584a500-98c5-11e4-96f5-e90e346a7b87.png)

**Comment by petrklus** [comment]
Odd - any reason why the devices would stop sending such commands in general? I've now separated the log file for zwave into a separate file, will wait for 10-12h and see if I see anything.

**Comment by cdjackson** [comment]
Assuming the wakeup command class is set, then it should wake up and send the notification.
Regarding sending the notification if you press the button - there's 2 things that can happen. If the wakeup command class is set, then it should work normally, but if the wakeup command class is not set
correctly (or at all) then the device will likely send a Node Info Frame (NIF) - this is not routable so will 
only work if the device is reasonably close to the controller (ie it must be able to talk directly).

**Comment by petrklus** [comment]
Ok, got an update - walked with the motion sensor right to the controller, and now I've got it showing up properly - so it was probably the case of Node Info frames. What do I need to do to set the wakeup command class properly?

**Comment by cdjackson** [comment]
Two options. If you're using a reasonably recent version of the binding (last couple of weeks), then set the config option "zwave:masterController=true", and when it completes initialisation, as part of the initialisation it will set the wakeup (lots of people forgot about this, so I automated it). It should set the time to whatever is already there, and the node to point to the controller.
Alternatively, once it's completed initialisation, use HABmin to set the wakeup time - it will automatically set the node as well.

**Comment by cdjackson** [comment]
Closing as no feedback for many months.
