### ISSUE TITLE
No database entry: Vision Security [ID:205,Type:2002]

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin#204]
There is no entry found on the database for this device.

Is there a plan to dissociate the product database from the compiled binding file allowing to update it with an external XML file in the future?

Thanks!

**Comment by cdjackson** [comment]
> Is there a plan to dissociate the product database from the compiled binding file allowing to update it with an external XML file in the future?
> 
No - I prefer to keep it within the binding so that it’s covered within the version control. If someone makes an error in the database, it is possible to cause problems to both the binding, and the devices, so it needs to be controlled.  It’s not hard to produce the XML files, and it’s easy to produce a PR for the changes.

**Comment by Togeole** [comment]
Indeed.

Thanks for your swift answer.

**Comment by Togeole** [comment]
So, I have a Vision ZP3102 with Device Id = 205 (Manufacturer Id = 109, Device Type= 2002) and the config is not loaded  from the database.

Note it was sold as a ZP3102 with a temperature sensor. When I look at pepper1, I think it's this one http://www.pepper1.net/zwavedb/device/358 (Product Id 202) known as ZD3102 (this reference is unfortunately not known on the manufacturer site).

In the product explorer in Habmin, I find the ZP3102 without multilevel_sensor so I imagine it's not the right one.

Can you please have a look and add this last with Product Id = 205?

Many thanks in advance!

**Comment by cdjackson** [comment]
Done - it should be in tomorrows snapshots…

**Comment by Togeole** [comment]
Thanks a lot !

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : lundi 12 janvier 2015 17:52
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] No database entry: Vision Security [ID:205,Type:2002] (#204)

Done - it should be in tomorrows snapshots…
