### ISSUE TITLE
[documentation] USB-stick further documentation

### ISSUE THREAD

**Issue by petrklus** [cdjackson/HABmin#205]
Hi,

When looking at https://github.com/openhab/openhab/wiki/Z-Wave-Binding, I am seeing that all USB controllers with "No remarks" should be all working. However, I have a few issues with the Aeon Labs Z-stick.

For me, the issue is when using include/exclude functions of the API (and the stick freezing later in 24-48h). The workaround is to physically unplug the stick after any network modifications and resetting - it seems to be OK from then on in my setup.

My main question is - is there any more detailed comparison between the sticks on a reliability level? I just want to know which one to get that does not have any known bugs in the firmware / or is well supported by the manufacturer.

More info from others on the Z-stick:

https://groups.google.com/forum/#!searchin/openzwave/Aeon$20Labs/openzwave/oM7VTuRVqv8/bztHcUOlH5kJ

**Comment by cdjackson** [comment]
Hi Petr,
Yes - the Aeon has some issues and I would probably avoid it. That said, the include button and internal battery are very nice features, but Aeon stuff does seem buggy (the multi sensor also has problems that they don’t want to, or can’t fix). Personally, I use the Aeon S2 and it’s mostly ok - it might hang every month or three, but it is quite rare. I also have a Sigma UZB-1 (ZWave Plus) and this is also working fine,but I only use it on my development system at the moment. The ZWave plus devices don’t like the soft reset for some reason, but that’s not a major issue.

A few people are starting to use some ZWave.me ZWave plus devices which is similar to the Sigma USB-1 - I’ve not heard anything bad, so I assume they are also ok.

Chris

**Comment by petrklus** [comment]
Ok, so which one would you recommend if I was after reliability only? I saw that the ZWave.me has some controller backup and in-field firmware upgrade features, which sound quite nice as well!

**Comment by cdjackson** [comment]
I’m not sure to be honest. Aeon is the only one that I know of that has a problem.
The Sigma seems ok, but I’ve not used it for an extended duration. Gilles is using one I think - as far as I know, it's working well, but it you might be better putting a message on the openhab list to see what people are using now - it would be very interesting I think.

**Comment by petrklus** [comment]
@cdjackson Started discussion here.. https://groups.google.com/forum/#!topic/openhab/jWZy-HLkfV8

**Comment by cdjackson** [comment]
Discussion was transferred. Closing this issue.
