### ISSUE TITLE
[question] BeNEXT Scene controller

### ISSUE THREAD

**Issue by petrklus** [cdjackson/HABmin#208]
Hello!

I've purchased BeNEXT scene controller (remote with 7 buttons) in a hope to use it to trigger events in openhab. However, despite my best efforts, I am unable to get it included into the network. 

I am using Aeon USB stick and I've tried inclusion with HABmin, with ozwcp, as well as with the manual button on the stick - absolutely nothing. And there is no problem with device inclusion in general - at the same time I was able to include new motion sensor without any trouble.

Here is the manual of the stick I am using:

http://www.benext.eu/static/manual/scenecontroller.pdf

Does anyone have any experience with this device?

**Comment by cdjackson** [comment]
Very old ZWave issue - update database if not resolved.
