### ISSUE TITLE
Qubino - Flush 1 Relay, no power/energy usage visible...?

### ISSUE THREAD

**Issue by larhedse** [cdjackson/HABmin#211]
Hi,

As a complete newbie at OpenHAB, I have just installed a Ubuntu 14.04LTS Server, with OpenHAB 1.6.1 and HABmin (latest I think, it includes zwave 1.7 snapshot binding).

I have some minor issues to get my Qubino flush 1 relay to return power usage (and from earlier testing I can not get temp reading either). The item file looks like:

Number  Power_EnkelBrytare      "Qubino Enkel Brytande forbrukning [%.1f W]"    <energy>        (Energi)                { zwave="5:command=meter,meter_scale=E_W" }

Since I have a greenwave device (you might know the "6-channel" version where every "channel" has energy/power consumption monitoring) and that one works (although the update frequence seems very slow), I am sure the syntax is correct.

If I add a :1 in the zwave binding:
{ zwave="5:1:command=meter,meter_scale=E_W" }

I will end up with an error in the openhab.log file... So that is not the reason.

Looking in the "manual" for the Qubino flush 1 relay, it says:
COMMAND_CLASS_METER_V3
COMMAND_CLASS_SENSOR_MULTILEVEL_V3
COMMAND_CLASS_MULTI_CHANNEL_V2
But how do I adress this METER_V3? Or is that done automaticly in the background?

Anyway I have had my share of problems with HABmin refusing to write down configs (I think it may have with ÅÄÖ to do, or samthing else, like mandatory fields?), so I nowdays add everything manually to the config files. That said, I am impressed with how good this works anyways - thanks for all hard work!!!

**Comment by cdjackson** [comment]
> Number Power_EnkelBrytare "Qubino Enkel Brytande forbrukning [%.1f W]" (Energi) { zwave="5:command=meter,meter_scale=E_W” }
If I remember correctly, you need to use the numbers for meter_scale - that’s certainly the case for other parameters so I assume it’s the same here. (worth a try).

> But how do I adress this METER_V3? Or is that done automaticly in the background?
> 
Yes - that happens in the background.

> Anyway I have had my share of problems with HABmin refusing to write down configs (I think it may have with ÅÄÖ to do, or samthing else, like mandatory fields?)
> 
I don’t know what AAO means??


What I’d suggest is capturing a DEBUG log file and sending it to me - just so long as it captures some incoming data. Email it to me at chris =at= cd-jackson.com=

**Comment by larhedse** [comment]
Well I have found the following:

ÅÄÖåäö - which is the swedish local characters can not be part of any of the fields. If I include local swedish characters then HABmin will fail (however it does not say why it fails).

There seem to be mandatory fields, if they do not have a value, then HABmin fails (however it does not say why it fails).

And since I already use Number in front of the definition, what is your exact suggestion? The syntax is correct - it just does not read the value.

Due to OpenHAB overloading my Fibaro HC2 with a lot of z-wave trafic..., I had to take OpenHAB DOWN so I can not provide any logs...

**Comment by cdjackson** [comment]
I’m not sure where you are typing these characters? It’s difficult to say what your problem is without more information- for example, you say ‘there seem to be mandatory fields’ - what are you talking about? Is this item configuration or what? Please can you provide a bit more information as to what you’re trying to do.

In general, most of HABmin ought to be UTF8 compliant so should work fine with different character sets, but there are probably some limitations...=

**Comment by cdjackson** [comment]
Stale issue
