### ISSUE TITLE
can anybody add ZME_064374 to zwave productdatabese

### ISSUE THREAD

**Issue by dl3mrk** [cdjackson/HABmin#212]
Hello,
can anybody add the device to the productdatabase?

http://www.pepper1.net/zwavedb/device/567
http://manuals.zwaveeurope.com/make.php?lang=en&type=&sku=ZME_064374

best regarts
Markus

**Comment by cdjackson** [comment]
This should be in snapshots tomorrow.

**Comment by dl3mrk** [comment]
works fine
thx

Am 31.01.2015 um 23:25 schrieb Chris Jackson:

**Comment by cdjackson** [comment]
Thanks
