### ISSUE TITLE
Database addition for TKB switch

### ISSUE THREAD

**Issue by solucionesmipc** [cdjackson/HABmin#215]
No database entry for tkb06 switch http://www.tkbhome.com/?cn-p-d-254.html id:4 type:1

**Comment by cdjackson** [comment]
This is already in the database.

**Comment by solucionesmipc** [comment]
Hi, thanks for fast answer, i see in newest database tz65d, tz66d, tz67, tz 68, and hsm02; 
it is "TZ06"  wall dual relay.
In habmin interface i  can not manage associations.
do i need associations to auto update the relay state in web interface?

thanks again ...

**Comment by cdjackson** [comment]
The TZ06 was added 7 days ago, so it should show up. 
https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/database/tkb/tz06.xml <https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/database/tkb/tz06.xml>

Generally, yes, you need associations for auto update…

What shows up in HABmin? Can you attach a screen dump?

**Comment by solucionesmipc** [comment]
Hi, every thing is fine now, i had an old habmin version.
associations now is ok too.

thanks a lot


diego
