### ISSUE TITLE
Missing device Secure SCS-317 in product database

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin#216]
Hi Chris, 

Can you please add the following device in the product database?

Thermostat Secure SCS-317

Thanks a lot!

**Comment by cdjackson** [comment]
Please provide the type/id that HABmin shows.

**Comment by Togeole** [comment]
Hi Chris,

Device ID =  1 and Device Type = 4

It has been recognized in Habmin under Manufacturer ID = 59 (Horstmann Controls).
In fact, this is this device (Horstnamm C-Stat ZW): http://www.horstmann.co.uk/products/wireless-products/wireless-controls/c-stat-11-17-zw

This is the same as the device I have branded under Secure Together: http://www.securetogether.com/files/9914/1447/2703/SCS317_User_-_P85163_1_WEB.pdf

Thanks.

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : samedi 7 février 2015 12:06
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] Missing device Secure SCS-317 in product database (#216)

Please provide the type/id that HABmin shows.

**Comment by cdjackson** [comment]
Thanks - I’ll add this as the Horstman since I can’t have multiple manufacturers with the same id…

**Comment by Togeole** [comment]
Horstmann is perfect ☺

Thanks !

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : dimanche 8 février 2015 15:14
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] Missing device Secure SCS-317 in product database (#216)

Thanks - I’ll add this as the Horstman since I can’t have multiple manufacturers with the same id…

**Comment by cdjackson** [comment]
I used the info on pepper1 for the configuration - I’m not 100% sure it’s correct as one of the values says it can be set from 0.1 to 50.0 deg in 0.1 steps, but it’s only 1 byte (which is max 255 steps!). Also, the min and max temperature defaults are both showing 5C - this doesn’t matter, but it indicates the information is probably not correct…

Anyway, it will be merged today, so if you find an error please let me know and I’ll update it.

**Comment by Togeole** [comment]
Ok, thanks. I’ll try and I let you know.

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : dimanche 8 février 2015 15:28
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] Missing device Secure SCS-317 in product database (#216)

I used the info on pepper1 for the configuration - I’m not 100% sure it’s correct as one of the values says it can be set from 0.1 to 50.0 deg in 0.1 steps, but it’s only 1 byte (which is max 255 steps!). Also, the min and max temperature defaults are both showing 5C - this doesn’t matter, but it indicates the information is probably not correct…

Anyway, it will be merged today, so if you find an error please let me know and I’ll update it.

**Comment by Togeole** [comment]
Hi Chris, 

It works correctly.

For the Delta T parameter, I see this on http://manuals.zwaveeurope.com/:

Delta T: Temperature change (Parameter Number 4, Parameter Size 1)
Change between temperatures to trigger a temperature report (step 0.1)
Value	Description
1 — 50	1 or 0.1 (Default 5 = 0,5°C) -> (1˚C = 10)

The description could be better :)

Min. and Max. default values are indeed 5.

I let you close this topic yourself just in case you would like to update the description.

Thanks a lot!

**Comment by cdjackson** [comment]
Thanks - I'll leave it at that...
