### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException exception present in zwave.log

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin#217]
Hello,

I'm just copy and paste error from zwave.log file. Maybe you will know to what it reffers:

```2015-02-06 22:50:32.444 ERROR o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1271]- Got an exception during receiving. exiting thread.
java.lang.ArrayIndexOutOfBoundsException: 6
        at org.openhab.binding.zwave.internal.protocol.SerialMessage.getMessagePayloadByte(SerialMessage.java:301)
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiLevelSensorCommandClass.handleApplicationCommandRequest(ZWaveMultiLevelSensorCommandClass.java:129)
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:80)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:188)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:168)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$12(ZWaveController.java:162)
2015-02-06 22:50:32.445 DEBUG o.o.b.z.i.p.ZWaveController$ZWaveReceiveThread[:1273]- Stopped Z-Wave receive thread```

**Comment by cdjackson** [comment]
What version of the binding are you using? The line numbers don’t seem to tie up so I think it’s not the latest?

**Comment by grzech1983** [comment]
My mistake. I'm using script for updating OH from cloudbees and I had to uncomment updating also zwave binding so error came from cloudbees version of binding. Latest binding from habmin package returns this error:

2015-02-08 16:46:04.535 ERROR o.o.b.z.i.p.ZWaveController[:286]- NODE 15: Error deserialising XML file. com.thoughtworks.xstream.converters.ConversionException: Could not set field class org.openhab.binding$
---- Debugging information ----
message             : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass.endpoint : null
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass.endpoint : null
class               : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass
required-type       : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /node/supportedCommandClasses/entry[4]/multiInstanceCommandClass/endpoints/entry/endPoint/supportedCommandClasses/entry/basicCommandClass/endpoint
line number         : 88
class[1]            : java.util.HashMap
converter-type[1]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.ZWaveEndpoint
class[3]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiInstanceCommandClass
class[4]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------

---- Debugging information ----
message             : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass.endpoint : null
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass.endpoint : null
class               : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass
required-type       : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /node/supportedCommandClasses/entry[2]/multiInstanceCommandClass/endpoints/entry/endPoint/supportedCommandClasses/entry/binarySwitchCommandClass/endpoint
line number         : 45
class[1]            : java.util.HashMap
converter-type[1]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.ZWaveEndpoint
class[3]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiInstanceCommandClass
class[4]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------

2015-02-08 16:46:05.276 ERROR o.o.b.z.i.p.ZWaveController[:286]- NODE 24: Error deserialising XML file. com.thoughtworks.xstream.converters.ConversionException: Could not set field class org.openhab.binding$
---- Debugging information ----
message             : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass.endpoint : null
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass.endpoint : null
class               : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass
required-type       : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBasicCommandClass
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /node/supportedCommandClasses/entry[4]/multiInstanceCommandClass/endpoints/entry/endPoint/supportedCommandClasses/entry/basicCommandClass/endpoint
line number         : 81
class[1]            : java.util.HashMap
converter-type[1]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.ZWaveEndpoint
class[3]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiInstanceCommandClass
class[4]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------

2015-02-08 16:46:07.176 ERROR o.o.b.z.i.p.ZWaveController[:286]- NODE 44: Error deserialising XML file. com.thoughtworks.xstream.converters.ConversionException: Could not set field class org.openhab.binding$
---- Debugging information ----
message             : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass.endpoint : null
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Could not set field class org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass.endpoint : null
class               : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass
required-type       : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveBinarySwitchCommandClass
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /node/supportedCommandClasses/entry[2]/multiInstanceCommandClass/endpoints/entry/endPoint/supportedCommandClasses/entry/binarySwitchCommandClass/endpoint
line number         : 45
class[1]            : java.util.HashMap
converter-type[1]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.ZWaveEndpoint
class[3]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiInstanceCommandClass
class[4]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------

2015-02-08 16:46:07.467 ERROR o.o.b.z.i.p.ZWaveController[:286]- NODE 56: Error deserialising XML file. com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.RuntimeException
cause-message       : null
class               : java.util.HashMap
required-type       : java.util.HashMap
converter-type      : com.thoughtworks.xstream.converters.collections.MapConverter
path                : /node/supportedCommandClasses/entry[5]/multiLevelSensorCommandClass/sensors/sensorType
line number         : 53
class[1]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiLevelSensorCommandClass
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------

2015-02-08 16:46:08.723 ERROR o.o.b.z.i.p.ZWaveController[:286]- NODE 65: Error deserialising XML file. com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No s$
---- Debugging information ----
field               : this$0
class               : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveAlarmSensorCommandClass$Alarm
required-type       : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveAlarmSensorCommandClass$Alarm
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /node/supportedCommandClasses/entry/alarmSensorCommandClass/alarms/entry/alarmSensor/outer-class
line number         : 28
class[1]            : java.util.HashMap
converter-type[1]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveAlarmSensorCommandClass
class[3]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------

**Comment by cdjackson** [comment]
Don’t worry about these XML ‘errors’. This can happen from time to time - I’ve changed the XML format slightly and there’s code to detect this, and reinitialise the device.

**Comment by grzech1983** [comment]
Ok. Closing.
