### ISSUE TITLE
No command class defined for ASR-ZW

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin#219]
Hi Chris, 

I see there is no command class defined in product explorer for the device ASR-ZW:
http://www.pepper1.net/zwavedb/device/46

Nevertheless, I have created an item (switch_binary) and it does not work.

Can the binding work without command class defined in the product database?

Thanks in advance for your answer.

**Comment by cdjackson** [comment]
> Can the binding work without command class defined in the product database?
> 
Yes - the command classes listed in the database are not really used in most cases - unless special configuration needs to be performed. This shouldn’t stop the device being used...

**Comment by Togeole** [comment]
Ok, thanks.

So I close the issue :)
