### ISSUE TITLE
Data are cut to half of the chart for switch items

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin#220]
Hello, 

I have a strange behavior with data coming from switch items.
They are systematically cut to half of the requested period in the graph as well as in the data Table in Habmin (where OFF and ON are respectively well replaced by 0 or 1).

Note I don't have this issue with Habmin2.

Any idea where is the problem?

Thanks.

**Comment by cdjackson** [comment]
Hi,
I’m not sure I understand what you mean - cn you provide a picture?

Chris

**Comment by Togeole** [comment]
Indeed, my description was fairly brief ☺

So, all screenshots were taken at 9:00 p.m. local (21h00) and data is OK in the persistence service (= MySQL).

On the habmin_chart_scale1.png, the actuator graph is “broken” at the arrow, right in the middle.
On the habmin_chart_scale2.png, the actuator graph is also “broken” at the arrow, right in the middle.

In both cases, there is no issue with temperatures.

You can see the same behavior on another chart habmin_chart_actuator_only.png with the actuator item only where period = period of habmin_chart_scale1.png.
It’s more difficult to see it here because the X axis is scaled where the data  is “broken” (around 9:00 am).
Therefore, it’s not possible to navigate to the current time on this chart because no data at all is shown in the Habmin Table as from the middle of the requested period.

The same behavior also occurs with other OFF/ON switches (e.g. Nikobus lights) whatever the recording interval (every minute, 10 minutes, etc.).
I did not try with OPEN/CLOSED switches (e.g. Motion detectors).

This is OK with Habmin2 (habmin2_chart.png).

I have tried to replace highcharts(-more).js with the newer version available on highcharts.com but it does not help.
The problem is the same by displaying the graph via the file chart.html.

So, I think the issue is somewhere in the getJSON function in the jquery.min.js file but I may be completely wrong.

Many thanks in advance for your help.

Vincent

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : mercredi 18 février 2015 19:55
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] Data are cut to half of the chart for switch items (#220)

Hi,
I’m not sure I understand what you mean - cn you provide a picture?

Chris

**Comment by Togeole** [comment]
![habmin_chart_actuator_only](https://cloud.githubusercontent.com/assets/10379912/6256615/db2d3362-b7b9-11e4-8cea-5dc822dad750.png)
![habmin_chart_scale2](https://cloud.githubusercontent.com/assets/10379912/6256616/db2d8812-b7b9-11e4-8062-3919f6f2943b.png)
![habmin_chart_scale1](https://cloud.githubusercontent.com/assets/10379912/6256617/db2ee7e8-b7b9-11e4-8b15-3d9a2f5a7c34.png)
![habmin2_chart](https://cloud.githubusercontent.com/assets/10379912/6256618/db2f2a1e-b7b9-11e4-9b3b-c1c032d4d921.png)

**Comment by Togeole** [comment]
Hi Chris, 

I'm a little bit lost because I finally don't know how data is retrieved from the persistence service to create the graphs.

Can you please help me?

Thanks.

**Comment by cdjackson** [comment]
Both HABmin and HABmin2 get the data from exactly the same place, so I don't think this is an issue with the way data is retrieved.
If you run the debugger, is there any error shown? Also, in the debugger you will be able to see the data being returned from openhab so you can see if it's wrong.

Another possibility is timezone issues or something like that but I guess you're in Europe so that's probably not the issue (and it should affect all channels not just one).

**Comment by Togeole** [comment]
Indeed, both URL’s below requested by Habmin when creating the graph give the same amount of data :

/services/habmin/persistence/services/mysql/Thermostat_Actionneur?_dc=1424591364084&starttime=1424504964023&endtime=1424591364023
<history>
<name>Thermostat_Actionneur</name>
<type>SwitchItem</type>
<statemax>1.0</statemax>
<timemax>1424504937000</timemax>
<statemin>0.0</statemin>
<timemin>1424505117000</timemin>
<stateavg>0.41539528432732314</stateavg>
<datapoints>1442</datapoints>

/services/habmin/persistence/services/mysql/Thermostat_Temperature?_dc=1424591364084&starttime=1424504964023&endtime=1424591364023
<history>
<name>Thermostat_Temperature</name>
<type>NumberItem</type>
<statemax>21.9</statemax>
<timemax>1424582700000</timemax>
<statemin>20.5</statemin>
<timemin>1424558639000</timemin>
<stateavg>21.22662968099857</stateavg>
<datapoints>1442</datapoints>

So the issue is not there.

Below the DEBUG log & sample Items table in MySQL but all seems also OK.

ItemId,ItemName
1,Meteo_Temperature
28,Valve_0_LIVFR
36,Valve_0_KITC1
38,Valve_0_LIVBA
50,Thermostat_Temperature
51,Thermostat_Setpoint
52,Thermostat_Actionneur

11:29:09.015 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Setpoint
11:29:09.015 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Temperature
11:29:09.015 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item51 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.015 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Meteo_Temperature
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item50 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item1 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 16ms
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Setpoint
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 16ms
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Temperature
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item51 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 16ms
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item50 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Meteo_Temperature
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVFR
11:29:09.031 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Actionneur
11:29:09.046 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVBA
11:29:09.046 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item52 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.046 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item1 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.046 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item28 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.062 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item38 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.062 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 143 rows in 31ms
11:29:09.062 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 31ms
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1439 rows in 47ms
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 47ms
11:29:09.078 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 1441 rows in 63ms
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVFR
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item28 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1439 rows in 47ms
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 32ms
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVBA
11:29:09.078 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 145 rows in 63ms
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item38 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.078 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 144 rows in 0ms
11:29:09.078 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 146 rows in 47ms
11:29:09.093 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 1441 rows in 78ms
11:29:09.093 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 144 rows in 15ms
11:29:09.093 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Actionneur
11:29:09.125 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item52 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.125 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 146 rows in 79ms
11:29:09.140 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1439 rows in 15ms
11:29:09.140 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 1441 rows in 109ms
11:29:09.171 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_KITC1
11:29:09.171 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item36 WHERE TIME<'2015-02-21 11:28:07' ORDER BY Time DESC LIMIT 0,1
11:29:09.171 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 0ms
11:29:09.187 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_KITC1
11:29:09.187 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item36 WHERE TIME>'2015-02-21 11:28:07' AND TIME<'2015-02-22 11:28:07' ORDER BY Time ASC
11:29:09.187 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 144 rows in 0ms
11:29:09.187 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 146 rows in 16ms
11:29:10.437 [DEBUG] [eController$ZWaveReceiveThread:1237 ] - Receive Message = 01 05 00 13 2A 01 C2
11:29:10.437 [DEBUG] [b.z.i.protocol.ZWaveController:164  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 2A 01
11:29:10.437 [DEBUG] [b.z.i.p.s.SendDataMessageClass:57   ] - CallBack ID = 42
11:29:10.437 [DEBUG] [b.z.i.p.s.SendDataMessageClass:58   ] - Status = Transmission complete, no ACK received. (0x01)
11:29:10.437 [WARN ] [b.z.i.p.s.SendDataMessageClass:61   ] - Already processed another send data request for this callback Id, ignoring.
11:29:14.609 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Meteo_Temperature
11:29:14.625 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item1 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVFR
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 15ms
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Temperature
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVBA
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Actionneur
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Meteo_Temperature
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Setpoint
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item28 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item52 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item38 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 0ms
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item50 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.640 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 0ms
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item1 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item51 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Actionneur
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 16ms
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 16ms
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Temperature
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item52 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 0ms
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Thermostat_Setpoint
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVFR
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 39 rows in 0ms
11:29:14.656 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item51 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.671 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_LIVBA
11:29:14.671 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 41 rows in 62ms
11:29:14.671 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 391 rows in 15ms
11:29:14.671 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item50 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.671 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item28 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.671 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 391 rows in 15ms
11:29:14.671 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item38 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.671 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 393 rows in 31ms
11:29:14.687 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 393 rows in 62ms
11:29:14.687 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 39 rows in 16ms
11:29:14.703 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 391 rows in 32ms
11:29:14.703 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 39 rows in 32ms
11:29:14.703 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 41 rows in 63ms
11:29:14.703 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 393 rows in 63ms
11:29:14.703 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 41 rows in 63ms
11:29:14.843 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_KITC1
11:29:14.843 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item36 WHERE TIME<'2015-02-21 20:18:48' ORDER BY Time DESC LIMIT 0,1
11:29:14.843 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 1 rows in 0ms
11:29:14.859 [DEBUG] [.p.m.i.MysqlPersistenceService:533  ] - mySQL query: item is Valve_0_KITC1
11:29:14.859 [DEBUG] [.p.m.i.MysqlPersistenceService:593  ] - mySQL: SELECT Time, Value FROM Item36 WHERE TIME>'2015-02-21 20:18:48' AND TIME<'2015-02-22 02:49:55' ORDER BY Time ASC
11:29:14.859 [DEBUG] [.p.m.i.MysqlPersistenceService:633  ] - mySQL: query returned 39 rows in 0ms
11:29:14.859 [DEBUG] [.h.s.chart.PersistenceResource:465  ] - CHART: returned 41 rows in 16ms

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : dimanche 22 février 2015 10:52
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] Data are cut to half of the chart for switch items (#220)


Both HABmin and HABmin2 get the data from exactly the same place, so I don't think this is an issue with the way data is retrieved.
If you run the debugger, is there any error shown? Also, in the debugger you will be able to see the data being returned from openhab so you can see if it's wrong.

Another possibility is timezone issues or something like that but I guess you're in Europe so that's probably not the issue (and it should affect all channels not just one).
