### ISSUE TITLE
Missing device in Product Database (Manufacturer Id: 86, Product Id: 58)

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin#221]
Hi Chris, 

I have an KeyFob Gen5 Aeon Labs that is not recognized in Habmin (Manufacturer Id: 86, Product Id: 58).

This is this one:
http://www.pepper1.net/zwavedb/device/609

Strange because I find it in Product Explorer.

Can you please add it or tell me if it's already added?

Thanks.

**Comment by Togeole** [comment]
Unfortunately not recognized :(

**Comment by cdjackson** [comment]
No - there’s a similar one in the database, but it’s not quite the same in configuration. Can you email me the XML file please.

**Comment by Togeole** [comment]
Thanks ☺ The XML is attached.

De : Chris Jackson [mailto:notifications@github.com]
Envoyé : lundi 23 février 2015 22:09
À : cdjackson/HABmin
Cc : Vincent Quintin
Objet : Re: [HABmin] Missing device in Product Database (Manufacturer Id: 86, Product Id: 58) (#221)

No - there’s a similar one in the database, but it’s not quite the same in configuration. Can you email me the XML file please.

**Comment by cdjackson** [comment]
Ahhhh - stupid Gitub removes the file. Can you email it to me at chris -at- cd-jackson.com
