### ISSUE TITLE
Database Additon - Aeon Labs Smart Strip DSC11-ZWUS

### ISSUE THREAD

**Issue by hdonis** [cdjackson/HABmin#225]
Hi Chirs, 

When you get a moment do you mind adding the Aeon Labs Smart Strip DSC11-ZWUS to your database?

I'm going to email you the engineering specs since i cant see how to attache an item to this request. 

Thanks

hugo

**Comment by cdjackson** [comment]
Isn't this the one you said Martin had created already? If he's not supplied the XML, did he send you a test version of hte binding that he'd compiled? I think I saw something, but I'm not sure? If so, can you email this to me as I can probably extract the file from the JAR.

**Comment by hdonis** [comment]
I just emailed you the jar file that Martin had created. Keep in mind that it doesn't contain the device configuration parameters because i didn't have them available at the time of the initial request.

**Comment by cdjackson** [comment]
Hi,
I didn’t receive the JAR - maybe rename it to .DOC just in case it’s being caught by a virus scanner somewhere…

Chris

**Comment by hdonis** [comment]
I just sent it in a zip file

**Comment by cdjackson** [comment]
Can you tell me what HABmin is currently reporting for the type and ID (sorry if you've already supplied this).

**Comment by hdonis** [comment]
This is what i see in the XML file that HABmin created. 

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>0x1851407</homeId>
  <nodeId>19</nodeId>
  <version>4</version>
  <manufacturer>0x86</manufacturer>
  <deviceId>0xb</deviceId>
  <deviceType>0x3</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>

**Comment by hdonis** [comment]
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  "<homeId>0x1851407</homeId>"
  "<nodeId>19</nodeId>"
  "<version>4</version>"
  "<manufacturer>0x86</manufacturer>"
  "<deviceId>0xb</deviceId>"
  "<deviceType>0x3</deviceType>"
  "<listening>true</listening>"
  "<frequentlyListening>false</frequentlyListening>"
  "<routing>true</routing>"

**Comment by hdonis** [comment]
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  homeId>0x1851407</homeId>
  nodeId>19</nodeId>
  version>4</version>
  manufacturer>0x86</manufacturer>
  deviceId>0xb</deviceId>
  deviceType>0x3</deviceType>
  listening>true</listening>
  frequentlyListening>false</frequentlyListening>
  routing>true</routing>

**Comment by cdjackson** [comment]
Thanks - that’s what I was after.  I’ll try and merge this tonight so it should be in tomorrows snapshot.

**Comment by hdonis** [comment]
You The Man

Thanks again for all the help.

**Comment by hdonis** [comment]
In updated to the latest snapshot today and deleted the old node.xml file for the device.

i now see the device listed as "SmartStrip Smart Strip" but it has no information or configuration options attached to it. i tried viewing it in both HABmin & HABmin2. Both of them only show the device name and nothing else. 

It doesnt appear that a new "node.xml" file was created in the etc/zwave folde when it identified the device.

**Comment by cdjackson** [comment]
I think I've merged this without merging another change to the code that is also needed by this device.  I'll try and fix this morning.

**Comment by cdjackson** [comment]
Please try the latest version on the HABmin site.

**Comment by hdonis** [comment]
Installed your latest build and everything looks good. 

Thanks again for all your help.

**Comment by omatzyo** [comment]
Sorry to resurrect this, but I think there may have been a problem with the configuration of this device.  

For switch_binary, there are 4 switchable outlets that can be called out with no problem in openHAB. 1:1, 1:2, 1:3, 1:4... a fifth switch for the whole strip, zwave=1...

But when it comes to monitoring with meter, there are actually 6 outlets that can be seen.  And the numbers don't line us.  1 through 4 includes the two non-switched outlets.  3 and 4 in the meter correspond the 1 and 2 in switch.  5 and 6 WOULD correspond to switch 3 and 4, but as far as the meter is concerned these are not present.

I hope that was clear... I think perhaps the xml is the culprit?
