### ISSUE TITLE
Charting option request

### ISSUE THREAD

**Issue by airix1** [cdjackson/HABmin#228]
I know highcharts provides a lot of chart types and I don't expect you to support them all, but for power consumption and monitoring, stacked area, stacked column and pie charts could be very useful!

**Comment by cdjackson** [comment]
I'm not planning on adding this to HABmin. If you want to raise a similar request on the HABmin 2 site, then I'd be happy to look at it. I use a different library for graphing in HABmin2 and the options for configuring charts are better (I don't just meant the library - I mean the infrustructure I've written to allow configuration).

**Comment by airix1** [comment]
I understand.  I'll open an issue on HABmin2.

**Comment by cdjackson** [comment]
Thanks. I'll close this here.
