### ISSUE TITLE
Transformation Service for Javascript

### ISSUE THREAD

**Issue by friendofg** [cdjackson/HABmin#230]
Hi Chris,

I think the Javascript transformation uses the wrong syntax.
Syntax produced by HABmin:
Text item=heating label="State [JAVASCRIPT(heating.js):%s]" icon="heating"
but it should be:
Text item=heating label="State [JS(heating.js):%s]" icon="heating"

see:https://github.com/openhab/openhab/wiki/Transformations#java-script-transformation-service

**Comment by cdjackson** [comment]
Hopefully this is fixed now?

**Comment by friendofg** [comment]
Yes - thanks
