### ISSUE TITLE
Only-Chart-View?

### ISSUE THREAD

**Issue by LukeOwncloud** [cdjackson/HABmin#233]
Is it possible to provide a view which only shows a saved chart? The dynamic charts are so much better than the static one provided by openHAB. I'd like to show those charts without all the other configuration options habmin shows.

**Comment by cdjackson** [comment]
Currently you can put a chart into a dashboard, but you’d still have the title bar. Is this what you mean, or do you want to remove the titlebar as well?

**Comment by LukeOwncloud** [comment]
Dashboard sounds nice. Is it part of habmin or openHAB? I cannot find any documentation about it.

**Comment by cdjackson** [comment]
It’s part of HABmin2 (so therefore, not really documented :) ). There is a screenshot in the HABmin2 readme on Github though

I’ve just noticed that you posted this to the HABmin list though, so in that case, yes you can do what you want - https://github.com/cdjackson/HABmin/wiki/Charting#viewing-charts-in-sitemaps <https://github.com/cdjackson/HABmin/wiki/Charting#viewing-charts-in-sitemaps>

**Comment by LukeOwncloud** [comment]
Perfect. Exactly what I was looking for. Not sure why I did not find it by myself!

**Comment by LukeOwncloud** [comment]
Another tiny question: Why is the number of channels limited to 8?

**Comment by cdjackson** [comment]
> Another tiny question: Why is the number of channels limited to 8?
> 
Good question - I forget if there’s a limitation anywhere or not - it probably seemed like a good number at the time, but it’s also possible there may be something hardcoded somewhere (although I doubt that).  How many do you want? It would start to become difficult to read I think with lots of channels...

**Comment by LukeOwncloud** [comment]
I just found it: https://github.com/cdjackson/HABmin/blob/master/app/graph/itemList.js#L196
Changing that to 18 works just fine.

Yes, reading will get a little difficult and displaying a little slow. But I have a complex heating system which reports that many temperatures. I need them all in the same graph. But it is just me and I solved it for myself. Usually 8 should be a good limit.
