### ISSUE TITLE
No database entry: Fibaro System [ID:1002,Type:202]

### ISSUE THREAD

**Issue by Daidalios** [cdjackson/HABmin#234]
Hi everyone,

im trying to get my Fibaro FGS-221 to work, but Openhab tells me only the ID and Type in the Devices.
I know there is a xml for this device in the latest jar-Snapshot (org.openhab.binding.zwave-1.7.0-SNAPSHOT-201503080846)

What am i doing wrong? Or is there an bug or something?

Thanks in advise!

Dennis

**Comment by cdjackson** [comment]
Figaro use a lot of different sets of type/id so you might just have a different one that we have in the database (we already have quite a few). Please let me know what they are and I’ll take a look. Also, if HABmin tells the application version (in the Information folder) please also include that since there are a few versions of this device

Chris

**Comment by Daidalios** [comment]
The Information-Folder says Version 4; Protocol Version 8.2; Application Version 2.2.
Can i give you some more Infos?

Thank you very much for your help! :)

**Comment by cdjackson** [comment]
Just to be sure, can you confirm that this is a FGS221, type is showing as 202 and id as 1002? Sorry to ask as I'm sure you're correct, but I wan't to be 100% sure as this is a little different numbering than the other devices fro Fibaro...

**Comment by Daidalios** [comment]
oh wait a sec, now that you ask... The Article in the Store says FGS221.. BUT on the device it says "Fibar Group Relay Switch FGS222 EU v2.2"
Its the 2 Switches à 1,5 kW Version... Sorry for that... ill tell the Store Manager...

**Comment by Daidalios** [comment]
And there is no xml for the FGS222.... oh wow, sorry for the confusing... now... where do i get such a xml for the Jar-File? XD Or can you/anyone add it?

**Comment by Daidalios** [comment]
Or can i write and upload it myself? Writing shouldnt be that problem, but may anyone add something to that repo?

**Comment by cdjackson** [comment]
I imagine it's probably the same as the FGS221 - maybe a parameter or two different, but probably mostly the same. I just found a website in France that says they are the same so I'll use the same configuration file as the 221, and if/when we find a manual I can update it with any changes.

**Comment by Daidalios** [comment]
Thank you very much!

**Comment by cdjackson** [comment]
If you keep an eye on the link below, some time soon (maybe in the next hour or so) it should come up with a link to the latest version. Alternatively, if you download the latest snapshot from Cloudbees tomorrow it should be in there...

Let me know if it's ok...

**Comment by cdjackson** [comment]
https://github.com/openhab/openhab/pull/2509

**Comment by Daidalios** [comment]
Its working, thank you! :+1:

**Comment by cdjackson** [comment]
Great - thanks...
