### ISSUE TITLE
Add RFXCOM configuration

### ISSUE THREAD

**Issue by robertvanbregt** [cdjackson/HABmin#235]
This is a request to add the configuration of an RFXCOM device to the HABmin console.

To enable or disable protocols you need the RFXmngr program that is only available on Windows. To make it platform independent, it would be great if it was available in HABmin, just like the Z-Wave configuration.

Domotiga (https://www.domotiga.nl/projects/domotiga/wiki/RFXCom) has this functionality called RFXCom Commander.

This is a link to the source code
https://www.domotiga.nl/projects/domotiga/repository/revisions/master/entry/DomotiGa3/.src/CRFXComTRX.class

**Comment by cdjackson** [comment]
Hi,
I’m afraid that this is outside of the scope of HABmin. The configuration handlers that you mention for zwave are actually part of the zwave binding - not HABmin (although I wrote both, so it might be confusing). There is also part of the code in the UI part, but the big problem is that the RFX binding would need to be modified to add the core of this functionality.

I would suggest that it’s better to do this in an OH2 version of the binding, but I’d be happy to help if someone wanted to add the handlers to OH1 and then implement a UI - the big problem is that you would need to find someone to add this to the binding. I don’t know who is the primary maintainer for the RFX binding, but maybe it’s worth approaching them - I’d be happy to discuss it with them and yourself to help getting this included…

Let me know what you think…

Cheers
Chris

**Comment by digineut** [comment]
I don't feel an urgent need, it would just be a (major?) improvement to RFXCOM support. 

I have already contacted the author/developer of RFXCMD (http://rfxcmd.eu) and he provided me with a python script to enable and disable protocols. So anyone with some appropriate skills (the binding maintainer?) should be able to reverse engineer it.

I support your suggestion to put the effort in OH2, so it should not be added to OH1 in my opinion (fwiw).

**Comment by cdjackson** [comment]
Closing. This is out of scope of HABmin. As above - this should be implemented in OH2.
