### ISSUE TITLE
Database Edit - Aeon Labs Smart Strip DSC11-ZWUS

### ISSUE THREAD

**Issue by omatzyo** [cdjackson/HABmin#238]
Referring to Aeon Labs Smart Strip DSC11-ZWUS #225 
https://github.com/cdjackson/HABmin/issues/225

Sorry to resurrect this, but I think there may have been a problem with the configuration of this device.

For switch_binary, there are 4 switchable outlets that can be called out with no problem in openHAB. zwave=1:1, 1:2, 1:3, 1:4... a fifth switch can control the whole strip, zwave=1...

But when it comes to monitoring with meter, there are actually 6 outlets that can be seen. And (confusingly) the numbers don't line up. Metered outlets 1 through 4 includes the two non-switched outlets.  Metered outlets 3 and 4 correspond to 1 and 2 in switch.  Metered outlets 5 and 6 WOULD correspond to switched outlets 3 and 4, but as far as openHAB is concerned these are not present.

I hope that was clear... I think perhaps the xml is the culprit?

**Comment by cdjackson** [comment]
There isnt anything in the database definition that would prevent any endpoints being used.

When you say openhab thinks they aren't present,  what do you mean?

**Comment by omatzyo** [comment]
In that case, I'm terribly sorry to be using this reporting system.  Thank you for your time.

These lines are displayed in the log, and no data is populated for the last two outlets on the strip, metered items 5 and 6.  They correspond to switched items 3 and 4.
```
[WARN ] [.b.z.i.c.ZWaveConverterHandler] - No command class found for item = SmartStripPower5, command class name = meter, using 0 refresh interval.
[WARN ] [.b.z.i.c.ZWaveConverterHandler] - No command class found for item = SmartStripPower6, command class name = meter, using 0 refresh interval.
```
As opposed to the other 5 items which update correctly:
```
[INFO ] [runtime.busevents ] - SmartStripPower1 state updated to 0
```
All of them are configured the same way in items:
```
Number  SmartStripPower0    "Strip Total Power Consumption  [%.2f W]"   { zwave="8:command=meter,meter_scale=E_W,refresh_interval=60" }
Number  SmartStripPower1    "Strip 1 Power Consumption  [%.2f W]"   { zwave="8:1:command=meter,meter_scale=E_W,refresh_interval=60" }
Number  SmartStripPower2    "Strip 2 Power Consumption  [%.2f W]"   { zwave="8:2:command=meter,meter_scale=E_W,refresh_interval=60" }
Number  SmartStripPower3    "Strip 3 Power Consumption  [%.2f W]"   { zwave="8:3:command=meter,meter_scale=E_W,refresh_interval=60" }
Number  SmartStripPower4    "Strip 4 Power Consumption  [%.2f W]"   { zwave="8:4:command=meter,meter_scale=E_W,refresh_interval=60" }
Number  SmartStripPower5    "Strip A Power Consumption  [%.2f W]"   { zwave="8:5:command=meter,meter_scale=E_W,refresh_interval=60" }
Number  SmartStripPower6    "Strip B Power Consumption  [%.2f W]"   { zwave="8:6:command=meter,meter_scale=E_W,refresh_interval=60" }
```

**Comment by cdjackson** [comment]
I think this means that the device does not support these endpoints - but it doesn't get this information from the database, it gets it from querying the device itself...

Can you attach the XML file generated by the binding for this node?

**Comment by omatzyo** [comment]
Is there any way for me to get around that?   Here is the XML

https://www.dropbox.com/s/0bglgv5q8fkof09/node8.xml?dl=0

**Comment by cdjackson** [comment]
It might be possible to add this to the database, but it would be good to understand this a bit better as it's strange the device doesn't report all endpoints.

Do you have the engineering spec for this device, or something from Aeon that provides some more information?

Can you contact Aeon support and see if they can provide the engineering spec for this - they are normally quite responsive. I'll take a look at the database to see what's possible.

**Comment by omatzyo** [comment]
https://docs.google.com/viewer?a=v&pid=forums&srcid=MDM3NTIwMDUwMTA4OTkyOTEwNDQBMDYxMzcwNTY0NzgyMDczNjc3NTYBTzNUUGQ5cWFLMGdKATAuMQEBdjI

**Comment by omatzyo** [comment]
Here is a post that turned up and helped me understand what I was experiencing...  maybe it will shed some light...

http://forums.indigodomo.com/viewtopic.php?f=58&t=12595

**Comment by cdjackson** [comment]
Thanks - I’ll take a look at the database. I think I added the ability to add this…

**Comment by cdjackson** [comment]
See here -:
https://github.com/openhab/openhab/pull/2704

Once Cloudbees builds this, give it a try (hopefully in a few hours). No guarantees that this will work - I don't think I've tried this before...

You will also need to delete the XML file to reinitialise the device.

**Comment by omatzyo** [comment]
Unfortunately, that did not work.  Thank you for taking your time to help!

I also tried adding the endpoints manually to the newly created xml, with no luck.  I did notice that these endpoints don't show up in the z-way interface either.  I'm not sure where to go from here.

**Comment by omatzyo** [comment]
I just went back and looked at this again! Your change worked!  All of the outlets show up.  It's unfortunate that they have to be called out in a haphazard way, but they work.  The four switchable outlets work as expected and all six outlets now display power and energy meters.

Thank you again!

**Comment by cdjackson** [comment]
Great - thanks for letting me know :)
