### ISSUE TITLE
Database Addition - Aeon Labs  ZW080-A17 Siren

### ISSUE THREAD

**Issue by omatzyo** [cdjackson/HABmin#239]
Hi Chris,

When you get a moment would you mind adding the Aeon Labs ZW080-A17 Siren to the database?

Here is the engineering specs document:
https://www.dropbox.com/s/032gm5smybdji28/aeotec-zw080a17-engineering-spec.pdf?dl=0

Thank you!
Jay

**Comment by cdjackson** [comment]
Can you please provide the type and ID that HABmin displays for this device - I need this information before I can add it to the database.

**Comment by omatzyo** [comment]
ID:50,Type:104
Thanks so much for doing this.  I'm looking forward to trying out your 'command configuration' for zwave devices that I've read about elsewhere.

**Comment by omatzyo** [comment]
Works perfectly! The push config command too.  Thank you Chris!

**Comment by cdjackson** [comment]
Thanks.

**Comment by jaiden0** [comment]
Could someone please post any working openhab code for this device? I'm a noob and can't get mine to work.

**Comment by cdjackson** [comment]
Can I suggest you post on the openhab forum instead of raising a bug?  You will have a much wider audience.
