### ISSUE TITLE
Two Vision Security devices to add

### ISSUE THREAD

**Issue by id628** [cdjackson/HABmin#241]
Vision Security ID:803, Type 2008
http://www.monoprice.com/Product?c_id=122&cp_id=12212&cs_id=1221201&p_id=11994&seq=1&format=2

Vision Security ID:703, Type 2007
http://www.monoprice.com/Product?c_id=122&cp_id=12212&cs_id=1221201&p_id=11995&seq=1&format=2

My first post here... what else do you need?

**Comment by cdjackson** [comment]
Thanks. I'll add these - they don't seem to have any config or associations so I have all the information.
