### ISSUE TITLE
Issue with FGBS-001 and DS18B20 sensors

### ISSUE THREAD

**Issue by Togeole** [cdjackson/HABmin#243]
Hi Chris, 

Not sure you can help but I have 2 FGBS-001 on which I try to connect 1,2,3 or 4 DS18B20 sensors and I don't get them in Openhab. In the log, I have always the message "NODE 82: Number of endpoints = 2" (cf attached log) for IN1 & IN2 (SENSOR_BINARY) but no SENSOR_MULTILEVEL detected. Note that I'm sure of my wiring diagram because I have a 3rd FGBS-001 (older) that works perfectly.

I wondered if it had something to do with the bug I have found here: http://bugzilla.homeseer.com/bugzilla/show_bug.cgi?id=1408

Do you have any idea what I can do?

Many thanks in advance for your answer.

Vincent

**Comment by Togeole** [comment]
Arf, not possible to attach the log file :(

**Comment by cdjackson** [comment]
I’m not sure I can help here, but if you email me the log (chris@cd-jackson.com) I’ll take a look at it to see if there’s anything useful (I suspect not, but I’ll have a look).

**Comment by Togeole** [comment]
Hi Chris, 

In the meantime, I have replaced the FGBS module by a FGRGB module with 4 analog inputs.
The RGB led strip is working on it.

I have connected an analog temperature sensor (PT1000) on IN1.

Do you have any idea about the configuration of the item to retrieve the value now on this input?

I have tried {x:1,command=sensor_multilevel,sensor_type=4) but id does not seem to work.

Thanks!
