### ISSUE TITLE
Missing device Secure SCS302 in product database

### ISSUE THREAD

**Issue by Chel** [cdjackson/HABmin#246]
Hi Chris, I think that the above device is missing in the database; can it be added please? In openHab I'm getting the following:

    19:28:16.918 [DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 10: No database entry: Horstmann Controls [ID:2,Type:3]

It's the device found here (http://www.pepper1.net/zwavedb/device/44), which has apparently changed its name from ASR2-RF to SCS302 (and a few more details are available here: http://www.vesternet.com/z-wave-horstmann-z-wave-controlled-boiler-receiver-two-channels).

Is there anything else you need or want here?

Cheers,
Dan

**Comment by Chel** [comment]
Apologies, the new name is SSR302, not SCS302.

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by Chel** [comment]
Done: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/262

I uploaded the xml and changed the genericDeviceClass from being a GARAGE_DOOR to a THERMOSTAT, and the specificDeviceClass from SIMPLE_GARAGE_DOOR to blank. I hope I've done it right.

**Comment by Chel** [comment]
Oh and no configuration parameters - not sure if the device has any: http://www.vesternet.com/downloads/dl/file/id/517/product/507/z_wave_secure_boiler_receiver_two_channels_manual.pdf

**Comment by cdjackson** [comment]
Very old ZWave issue - update database if not resolved.
