### ISSUE TITLE
Z-wave network does not initialize with 1.7

### ISSUE THREAD

**Issue by maartendamen** [cdjackson/HABmin#247]
I am using the 1.7.0 snapshot version as suggested for the Openhab 1 installation. However, it seems that the z-wave network initialization does not complete. Using the 1.6 version of the z-wave binding the network does ultimately initialize and work just fine. I am using the Aeon Labs z-stick 2. 

One weird thing I noticed in the log file is that my z-stick is not recognized:

NODE 1: No database entry: Manufacturer:7328 [ID:1623,Type:21c2]

This is weird because is a widely used stick. 
I tried clearing up the node XML files but this does not help. I can provide the log file if required.

**Comment by cdjackson** [comment]
There won't be much I can do without a debug log... Clearly this isn't a general issue since most people are using this binding.

**Comment by maartendamen** [comment]
Can I send you this by e-mail or can I attach it here somehow?

**Comment by maartendamen** [comment]
I managed to fix it, this issue was due to a crashing stick. I removed the stick, cleaned up all files, locks etc. then reseated the stick. Everything is working like a charm now. Thanks for creating Habmin, great tool!
