### ISSUE TITLE
Missing device in database: Devolo Scene Switch MT2652, similar to ZWave.me Keyfob

### ISSUE THREAD

**Issue by JensErat** [cdjackson/HABmin#250]
The device [Devolo Scene Switch MT2652](http://products.z-wavealliance.org/products/1143) is missing in the database. It is pretty much a [ZWave.me Keyfob](http://products.z-wavealliance.org/products/1282) with another casing, they even forgot "Keyfob" somewhere in the documentation of the Scene Switch. I could not find _any_ differences in the specs nor documentation apart from vendor and product IDs.

The [XML file of the Keyfob](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/database/zwaveme/kfob.xml) can be taken as is, replacing the name and model elements (_MT2652_ respective _Scene Switch_?).

Manufacturer ID is 175, as expected for Devolo.

I hope I got the element for the products.xml right:

```
		<Product>
			<Reference>
				<Type>0100</Type>
				<Id>0101</Id>
			</Reference>
			<Model>MT2652</Model>
			<Label lang="en">Scene Switch</Label>
			<ConfigFile>devolo/mT2652.xml</ConfigFile>
		</Product>
```

**Comment by cdjackson** [comment]
Thanks - I've added that - hopefully I got the right one :)

It should be in tomorrows snapshot - let me know if it's ok...

**Comment by JensErat** [comment]
That was fasat! I will probably verify the nightlies on Sunday. The commit also includes a removed file but no comment indicating so, was this intended?

**Comment by cdjackson** [comment]
Hi,
Yes - I removed an unused file as well…

Cheers
Chris

**Comment by JensErat** [comment]
Hi Chris,

I've successfully included and configured one of the switches. Did not try all functions yet, but seems fine so far. Closing the issue, if I find any problems I'll get back to you.

Including these switches is a hassle as the battery power drops for a while after each reconfiguration, I'd love to have thicker ones with reasonable batteries instead...
