### ISSUE TITLE
Possible bug in product database for Philio PAN06-1A

### ISSUE THREAD

**Issue by rom169** [cdjackson/HABmin#258]
The Philio PAN06-1A configuration is not pulled correctly out of the database. Habmin pulls PAN06-1 instead. Also Habmin product explorer does not show the device correctly.

I'm not a programmer, but I assume there is a bug in products.xml file in line 1963:
```
<ConfigFile>philio/pan06_1.xml</ConfigFile>
```
Should look like this:
```
<ConfigFile>philio/pan06_1a.xml</ConfigFile>
```
There are also some changes needed in pan06_1a.xml: 
Parameter 1 order is different:
```
<Item>
        <Value>1</Value>
        <Label lang="en">Relay 1</Label>
        <Label lang="de">Relais 1</Label>
</Item>
<Item>
        <Value>2</Value>
        <Label lang="en">Relay 2</Label>
        <Label lang="de">Relais 2</Label>
</Item>
<Item>
        <Value>3</Value>
        <Label lang="en">Relay 1 + 2</Label>
        <Label lang="de">Relais 1 + 2</Label>
</Item>
```
Parameter 1 default is different:
```
<Default>3</Default>
```
This change in line 3 would be most probably just cosmetics:
```
<Model>PAN06-1A</Model>
```

Regards
Rom169

**Comment by cdjackson** [comment]
Thanks - I’ve updated the database.

**Comment by rom169** [comment]
Thank you!
Why didn't you  change the parameter 1 value order and default?
Regards
rom69

**Comment by cdjackson** [comment]
> Why didn't you change the parameter 1 value order and default?

Because in the original email these requests weren't included. Did you edit the request after sending it? If so, Github doesn't send a new email, so I worked off the original request you made (as below) which doesn't mention anything about parameter 1.

>The Philio PAN06-1A configuration is not pulled correctly out of the database. Habmin pulls PAN06-1 instead. Also Habmin product explorer does not show the device correctly.

>I'm not a programmer, but I assume there is a bug in products.xml file in line 1963:
philio/pan06_1.xml
Should look like this:
philio/pan06_1a.xml

>This addional change in pan06_1a.xml in line 3 would be most probably just cosmetics:
PAN06-1
should look like this:
PAN06-1A

>Regards
Rom169

**Comment by rom169** [comment]
Yes I modified the post after I noticed the changed parameter order. 
I'm new to openhab and to github. 
Sorry!

**Comment by rom169** [comment]
Found another error today in pan06_1a.xml:
Parameter 4 can not be changed. Please modify type of parameter 4 to "byte".
Thank you
rom169

**Comment by rom169** [comment]
Created a pull request:
https://github.com/openhab/openhab/pull/3154
regards
rom169
