### ISSUE TITLE
Where is the source for org.openhab.io.habmin?

### ISSUE THREAD

**Issue by paixaop** [cdjackson/HABmin#261]
Chris where is the source for the REST Services part of Habmin? Do you make it available?

**Comment by cdjackson** [comment]
Yes it's in my oh repository.

**Comment by paixaop** [comment]
cloned your OH repo changed to the HABmin branch but when building it in the IDE I'm getting an error about DashboardWidgetOptionsBean not being found. What am I doing wrong?

**Comment by cdjackson** [comment]
Not sure. 

What are you wanting to do though. If you want to add support for the all in class then this needs to be done in the binding not Habmin.

**Comment by paixaop** [comment]
Just want to run openHab from the IDE with the Habmin and Zwave bindings enabled so I can debug SwitchAll configuration changes. Not changing anything in the the habmin binding it self.

**Comment by cdjackson** [comment]
No probs - feel free to change anything. I ws just worried you were looking to add support for the switch class which isn’t needed in HABmin…

I found the java file isn’t committed - I’ll add it shortly…
