### ISSUE TITLE
Missing device in database - PAN08-1

### ISSUE THREAD

**Issue by vectah0** [cdjackson/HABmin#262]
Hello,

I'm using rollershutter controller from Philio Technology Corporation. It's PAN08-1 (EU version). It seems that it's not included in database. I'm using latest 1.8.0 z-wave binding.

2015-08-30 19:50:48.051 [DEBUG] [.z.i.config.ZWaveConfiguration] - NODE 3: No database entry: Philio Technology Corporation [ID:6,Type:1]

Could you please add it to database?

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by cdjackson** [comment]
Very old ZWave issue - update database if not resolved.
