### ISSUE TITLE
Z-Wave New Device - Cooper RF9534

### ISSUE THREAD

**Issue by omatzyo** [cdjackson/HABmin#263]
Hi Chris,

When you have a moment please add the cooper switch (Cooper RF9534).  Here is the pepper1 link.  Do you need anything else?

http://www.pepper1.net/zwavedb/device/251

Thank you!

**Comment by cdjackson** [comment]
Is this in the online database (www.cd-jackson.com)? If not then please add there - I'll close this, but if you need help adding to the database then let's discuss on the forum.
