### ISSUE TITLE
Z-Wave Device not in database Switch GE 12730 (ZW4002)

### ISSUE THREAD

**Issue by typhoonss92** [cdjackson/HABmin#264]
Just signed up for this forum. Been configuring Openhab for about a year with arduino devices but moved to z-wave recently to see how it works. I had to get the 1.8 snapshot z-wave binding for my Remotec ZTS-110 thermostat that you just did about a month ago and it seems to work really good. 
I tried to setup the Eclipse multiple ways but keep getting errors so maybe having someone knowledgable like you help will speed up the process. Thanks for all the help in advance.  

I have added this to my system and I am able to turn on and off but from what I am reading I can not get pull requests until it is in the product database. 

once this is added would I be able to pull meter readings from this product?

Let me know if there is anything else you need from me to get this taken care of. 

ID:3034
Type:4944
Manufacturer ID:63
Multilevel_Switch
Here is the xml file under Openhab/etc/zwave
Not sure if this helps...

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_MULTILEVEL</specificDeviceClass>
  </deviceClass>
  <homeId>0xdb9ea224</homeId>
  <nodeId>3</nodeId>
  <version>4</version>
  <manufacturer>0x63</manufacturer>
  <deviceId>0x3034</deviceId>
  <deviceType>0x4944</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2015-09-14T17:30:19+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_CONTROLLER_BRIDGE</libraryType>
        <protocolVersion>3.67</protocolVersion>
        <applicationVersion>3.10</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>2</int>
  </nodeNeighbors>
  <lastSent>2015-09-14 17:30:15.778 UTC</lastSent>
  <lastReceived>2015-09-14 17:30:15.838 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by typhoonss92** [comment]
I was wondering how to get new z-wave items added. It said in the Openhab documentation to put in requests here but I have not had a response to this or seen it added to any of the newer nightly builds for the bindings. If anyone could chime in and let me know if there is other info needed or is there somewhere else I need to submit this info that would be very helpful. I am waiting to see if this gets added and works to purchase more of these switches. 
Thanks
Json

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by cdjackson** [comment]
Is this in the online database (www.cd-jackson.com)? If not then please add there - I'll close this, but if you need help adding to the database then let's discuss on the forum.
