### ISSUE TITLE
Everspring HSM02-1 support

### ISSUE THREAD

**Issue by saprize** [cdjackson/HABmin#266]
Hi im trying to get this window contact going but log says: 
[DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 5: No database entry: Manufacturer:278 [ID:1,Type:2]

zwave binding: 1.8.1 
habmin: 1.7.0

Thx

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by cdjackson** [comment]
Is this in the online database (www.cd-jackson.com)? If not then please add there - I'll close this, but if you need help adding to the database then let's discuss on the forum.
