### ISSUE TITLE
Zwave binding makes openhab "crash" (1.8 and 1.7.1)

### ISSUE THREAD

**Issue by tudstudent** [cdjackson/HABmin#267]
Ok, this is really odd behavior and I do really not know how to fix it myself. Have been busy with it for to many days now. I have eliminated a lot of other causes and it is clear when disabling z wave in the config (hash out /dev/ttyUSB0) everything except z wave works.

Zwave results in openhab not reading my items, no rules, no transforms, nothing (not visible in Habmin), but also the rules are not working.
However just switching a light (on/off) is working.

Openhab always ran fine on my Pi2 and since I upgraded to 1.7 and later to 1.7.1 and recently 1.8 it is really 1 big mess. It needs to be fixed one way or another, so please tell me how I can support with logs etc.
Currently none added because I do not know what you would like to have.

**Comment by cdjackson** [comment]
I’m not sure why this is a problem with HABmin, or for that matter the zwave binding. You really need to work this through and work out what is wrong and provide logs - I can’t do this for you sorry..

**Comment by tudstudent** [comment]
Chris, thank you for your reply. So far I have eliminated it by disabling the zwave binding. When disabled openhab works fine. If enabled it 9 out of 10 times jams the runtime and then only the zwave nodes which do not work based on a rule respond.

I am not quite sure how to further investigate. I can create the necessary logs...

**Comment by cdjackson** [comment]
Ok - I’ll take a look at the logs. I’ve not heard about this issue and since many people are using the system it may be something very specific to your system. However if you provide the logs I’ll take a quick look.

Really though, this shouldn’t be raised as a HABmin issue as I still don’t see how this can be a HABmin problem?

**Comment by tudstudent** [comment]
Generated the logs (zwave.log):
http://paste.ubuntu.com/12560197/

OpenHAB log (openHAB.log):
http://paste.ubuntu.com/12560192/

I posted here, because of the fact that last time with the duplication error on Pi1 it was discussed also on this hub.
I already looked through it, but in reality the rules are NOT working I cannot spot anything strange in the logs (as far as my knowledge goes).
Your help is kindly appreciated.

**Comment by cdjackson** [comment]
The RPi duplication wasn't discussed here I think. The discussions are on the openhab issue list - this list is for Habmin which has not changed for a while now. 

I'll take a quick look at your log when I get a chance.

**Comment by tudstudent** [comment]
You are totally right: https://github.com/openhab/openhab/issues/1564
(Should have done the search before posting but was totally convinced it should be here...)

**Comment by cdjackson** [comment]
I’ve had a look through the logs and can’t see anything wrong. ZWave appears to be working well - you have a couple of timeouts to some nodes very occasionally which is normal, but it looks fine.

**Comment by tudstudent** [comment]
Do you have any clue where I should look now, because it is quite odd that when zwave is disabled everything works like a charm and when zwave is enabled it jams all rules (and openhab displaying items and rules etc.)

**Comment by cdjackson** [comment]
Sorry - I’ve no idea. There is nothing at all in your logs to show any sort of problem and no-one else has the problem that you’re reporting (at least not that I know of anyway).

There was nearly no change to the zwave since 1.7, so it’s strange really that this has anything to do with zwave, and we have no other reports of it not working (again, that I know of).

**Comment by tudstudent** [comment]
Chris, just hypothetical, can it be that my zstick is ****ed-up by removing nodes via zensys.
The aeotec zstick is kinda pain in the **s, if it deals with removing nodes, you need to press replace, is alive and then remove.
Can this made the stick unstable, because only thing left I can think of is rejoining 7 nodes on a reset zstick... (which is not my favorite hobby)

**Comment by cdjackson** [comment]
I don’t think so, but who knows. It’s hard to say though since I don’t see any real problem. The stick looks like it’s working ok, but I have seen issues if you remove the zstick while OH is working, then OH can completely stop (is this what you’re seeing?). If you see this, then maybe there’s a problem with the stick, or the USB on the Pi, or something else in that sort of area.

**Comment by tudstudent** [comment]
Nope, it is happening while the stick is in the machine. I am aware when removing the stick while running openhab it will crash openhab. 
In my case openhab is not crashing, only not working as supposed (ps aux shows processes)
Well then I will just rejoin the devices and hope it will fix my problem (please please please ...)

**Comment by cdjackson** [comment]
Well, I’m really not sure then - sorry. There’s no indication of any error that I can see and really the zwave binding shouldn’t affect rules etc.

**Comment by tudstudent** [comment]
To bad, just updated the kernel on the Pi2, from 4.1.6-v7+ #810 SMP PREEMPT to 4.1.7-v7+ #817 SMP PREEMPT first try this, because rejoining is relly not my hobby ;)

**Comment by tudstudent** [comment]
@cdjackson I have been running normally after kernel update. I have no idea how this might have influenced openhab, but anyway I close this issue and if something as a real problem pops-up I will post in appropriate forum/github

**Comment by tudstudent** [comment]
Unfortunately 2 days ago the system crashed again with the zwave binding. OpenHab dit not show any items anymore. Since I was so done with this fact I decided to stop using the zwave plugin and combine openhab with MQTT (which I already used for different items).

Besides that I turned the Zwave stick to domoticz and joined all by MQTT. This way the "shed RPI" was running for months without problem, while the "House RPI" crashed.

Can be my hardware, but since it works well with Domoticz (RPI version 1 and 2) I still suspect something is buggy in the openhab & zwave build.

Even though this is a pity for me, my current setup is stable (fingers crossed) and would like to thank you for your support and of course keep up the good work!!!

**Comment by cdjackson** [comment]
Do you have any logs?

I’ve also seen something similar, but I never get an exception logged. I’m thinking that the issue might be in the serial driver which is out of our control, but I’m not sure. If it was in Java (i.e. the binding), then we should catch the exception and restart the threads.

**Comment by tudstudent** [comment]
I might actually have a log I think. Come back to this in a hour.

**Comment by cdjackson** [comment]
Thanks - would be good :)

**Comment by tudstudent** [comment]
Unfortunately earlier logs I do not have (overwrite on restart?)
Zwave: http://paste.ubuntu.com/13526101

I have openhab logs if needed. They are per date, so if needed let me know.

Btw: What do you mean with serial driver? How can it work in domoticz and not in this binding?

**Comment by cdjackson** [comment]
> Unfortunately earlier logs I do not have (overwrite on restart?)
> 
No- logs should be overwritten on restart.

> Btw: What do you mean with serial driver? How can it work in domoticz and not in this binding?
> 
I know nothing about domoticz, but I’m guessing at it’s OZW that it’s in C, and that it’s using a different serial driver. The driver is compiled into the binding, but it’s not something I can control, and it’s using low level functions which is why if it crashes, I suspect it would bypass all the java exception handling.

**Comment by tudstudent** [comment]
Domoticz is indeed OZW, then I understand your problem with the serial driver.

This is the only Zwave log I have and I did not change any setting.
