### ISSUE TITLE
ZS6101EU, class and value problem

### ISSUE THREAD

**Issue by Gilles76** [cdjackson/HABmin#269]
Hi Chris,

It's been a long time I want to write this issue. The ZS6101 do a mapping from sensor_binary class to basic class.

When I test with using sensor button, in the log I can see:

 NODE 89: Got a value event from Z-Wave network, endpoint = 0, command class = BASIC, value = 255
2015-10-09 15:10:40.504 WARN  o.o.b.z.i.c.ZWaveBasicConverter[:87]- No converter found for item = Detecteur_fumee_abris, node = 89 endpoint = 0, ignoring event.

Whereas my item is:

Number  Detecteur_fumee_abris   "Detecteur fumee abris [%d]"    { zwave="89:0:command=BASIC" }

Another remark is, in the log I can see that the basic value is 255 , but never see a zero value when test button is released.

Am I wrong ? or do you think there is something to do.

Thank you,

Gilles.

**Comment by cdjackson** [comment]
What happens if you change the item type to a switch (so it supports ON / OFF)?

**Comment by Gilles76** [comment]
Hi Chris,
I'll try it tomorrow and report you if it's better.

**Comment by Gilles76** [comment]
Again late sorry,

It's working with an item switch. For next time, I will try switch when a number not working.

If you are agree, I close this ticket.

Thank you for your advice.

**Comment by cdjackson** [comment]
This sort of issue is simplified in the OH2 binding - the converters aren't so fussy (completely rewritten).
