### ISSUE TITLE
Aeotec door sensor  state does not change

### ISSUE THREAD

**Issue by paragparandkar** [cdjackson/HABmin#270]
using 
Aeotec z stick gen 5, door sensor, openhab , habmin
door status always shows closed

curl http://localhost:80t/items/Door_Motion/state

 always give
CLOSED

item file -
 cat /usr/share/openhab/configurations/items/default.items 
Contact Door_Motion "Window [%s]" <window> (DollHouse) {zwave="2:command=SENSOR_BINARY,refesh_interval=1,respond_to_basic=true"}

openhab.cfg has following configuration for z wave binding
zwave:port=/dev/ttyACM0

habmin shows door sensor with green circle as node 2

configuration parameters for node are set as -
send sensory binary  reports on open close events - on for close, off for open
send basic also similar

door status value always comes as closed , even when door is open

**Comment by cdjackson** [comment]
Can I suggest closing this bug on HABmin (since this is nothing to do with HABmin) and asking your question on the openhab forum?

**Comment by cdjackson** [comment]
community.openhab.org

**Comment by paragparandkar** [comment]
thanks cd jackson.I will raise it in openhab forum.

can you comment if I am doing anything wrong here , i am new to openhub and do not see z wave detail logs in openhab log, to figure out where the problem is device or openhab or rest service layer

**Comment by cdjackson** [comment]
I don't see anything obviously wrong, but I'd need to see a log... If you post on the forum I'll take a look...

**Comment by paragparandkar** [comment]
Thanks CD jackson
Kindly find log at 
https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/8/8ce68213fe661931473f8c679b77bd1ec21ee7cf.pdf
