### ISSUE TITLE
please add lfm-20 to the library

### ISSUE THREAD

**Issue by rm65453** [cdjackson/HABmin#272]
![lfm-20](https://cloud.githubusercontent.com/assets/14905858/10419415/68a96bcc-7045-11e5-8e91-caa245fb4b16.png)

Thank you.

**Comment by cdjackson** [comment]
Please provide a link to the manual, and/or pepper1 database entry so that we can get the configuration.

**Comment by rm65453** [comment]
http://www.homeseer.com/pdfs/Evolve/LFM-20_SPEC.pdf

I have sent an email to the manufacturer to provide the configuration info.

**Comment by rm65453** [comment]
Just updated to jar file to the latest build and this still has not been resolved. node still showing up as a number with the device id and type showing up in numbers.

**Comment by rm65453** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/14905858/10708462/8834b67c-79d7-11e5-98e9-35446d36f362.png)

**Comment by rm65453** [comment]
it shows up under the product explorer but nothing is listed under it.

**Comment by cdjackson** [comment]
There is no information shown in HABmin because I don’t have the information to add - have you sent this to me? (apologies if I’ve missed it).

**Comment by rm65453** [comment]
No worriew. Below is the email from evolve. And a link to the manual.

http://www.homeseer.com/pdfs/Evolve/LFM-20_SPEC.pdf

"Hello,
Unfortunately the LFM-20 does not have any specific configuration parameters. Here are the supported Command Classes for the device:
Z-Wave Supported Command Classes: 
COMMAND_CLASS_SWITCH_BINARY
COMMAND_CLASS_SCENE_ACTIVATION
COMMAND_CLASS_SCENE_ACTUATOR_CONF
COMMAND_CLASS_SWITCH_ALL
COMMAND_CLASS_PROTECTION
COMMAND_CLASS_POWERLEVEL
COMMAND_CLASS_CONFIGURATION
COMMAND_CLASS_VERSION
COMMAND_CLASS_MANUFACTURER_SPECIFIC
• Z-Wave Controlled Command Classes: COMMAND_CLASS_SWITCH_MULTILEVEL
Please let us know if we can be of further assistance."

**Comment by cdjackson** [comment]
Yes, I have that, but this is of no use here. The device supports configuration (based on this list) but without information on the configuration, I can’t add anything. This is why there’s nothing in the database - unless we get this information, there’s nothing to do…

**Comment by rm65453** [comment]
So how can I find that info? Sorry if I am not of much help.

**Comment by cdjackson** [comment]
The only way to get the info is from the manufacturer. Maybe it doesn’t really support configuration parameters (despite it supporting the command class) - I’m not sure, but the information can only come from them.

**Comment by rm65453** [comment]
I have sent them another email. Will keep you posted.

**Comment by rm65453** [comment]
Found this. Not sure if this will helphttp://products.z-wavealliance.org/products/1007/pics

**Comment by rm65453** [comment]
And this

http://www.zwaver.net/0113_5246_3133.html

**Comment by cdjackson** [comment]
No - neither of these has any configuration information. It may simply be that the device has no configuration parameters…

**Comment by rm65453** [comment]
Also since this device is the same as the fsz20. Here is the pepper1 entry for it.

http://www.pepper1.net/zwavedb/device/479

**Comment by rm65453** [comment]
This one doesnt have it either. Can i still use the device with habmin?

**Comment by cdjackson** [comment]
> On 24 Oct 2015, at 13:32, rm65453 <notifications@github.com> wrote:
> 
> Also since this device is the same as the fsz20. Here is the pepper1 entry for it.
> 
> http://www.pepper1.net/zwavedb/device/479 <http://www.pepper1.net/zwavedb/device/479>
> 

Again, there’s no configuration, so maybe it’s simply not configurable.

**Comment by rm65453** [comment]
Shouldn't i still see the comand enteries under the command tab?

**Comment by cdjackson** [comment]
You can still use the device, of course. It’s just that there’s nothing to configure...

**Comment by cdjackson** [comment]
> On 24 Oct 2015, at 13:33, rm65453 <notifications@github.com> wrote:
> 
> Shouldn't i still see the comand enteries under the command tab?
> 
> 

No - I didn’t bother to configure them.

**Comment by rm65453** [comment]
Whenever i try to enter text in the name and location field ut just disappears. Also unlike the other devices this one just shows up as node 7. Anyway to fix that?

**Comment by cdjackson** [comment]
It should correctly show the device name once it’s added to the database. I suspect you are running an old version of the binding since these changes were only compiled early this morning and your emails were sent 10 minutes after the compilation completed (at around 03:30). So either you have an old version or you were just very quick :)

**Comment by rm65453** [comment]
Based on what i have read. This button needs to be configured as a momentary push switch to work properly as a garage opener. Dont think i would be able to do that with openhab

**Comment by rm65453** [comment]
I was very quick lol. I have been waiting for days for the compilation. Had the time marked on my calendar

**Comment by cdjackson** [comment]
Ok, so if there are configuration parameters, then you need to find what they are. As I said, they must come from the manufacturer - they are normally provided in the manual for every other device I’ve seen. So, for openhab, or any other system, you will need this information.

**Comment by rm65453** [comment]
Ok. Thanks again for all your help.

**Comment by cdjackson** [comment]
I found an error with the code - it's now updated.

Let me know if you get the config information...

**Comment by rm65453** [comment]
Turns out this device has like 4 different names depending on the seller. Homepro sells it as zrf113 and has (i think) the info you need.

https://www.smarthome-products.com/productspecs/ZRF113-Manual.pdf

**Comment by cdjackson** [comment]
Can you email this - for some reason the link doesn’t work here.

**Comment by rm65453** [comment]
Done

**Comment by cdjackson** [comment]
got it - thanks.

**Comment by rm65453** [comment]
Hope this helps.

**Comment by rm65453** [comment]
installed it 2 days ago on my garage door. works perfectly. thank you so much for all your help supporting new devices. much appreciated.
