### ISSUE TITLE
Question: Where zwave nodes names are stored?

### ISSUE THREAD

**Issue by unicornis-pl** [cdjackson/HABmin#273]
I had to recover the installation from backup and all the z-wave node names for the z-wave binding are gone. Where are they kept?

**Comment by cdjackson** [comment]
They are stored in the XML files for each node. You can set them in HABmin.

**Comment by unicornis-pl** [comment]
I have restored whole openhab directory tree, but z-wave node names are gone. Can you tell me what is the default path for the xml files? I cannot find them in the backup.
Thanks in advance.

**Comment by cdjackson** [comment]
they are in /etc/zwave. Note that they will automatically be regenerated.

**Comment by unicornis-pl** [comment]
What does it mean? After restart node names are gone? Are they stored in the controller (I am using USB stick). Apparently I do not have them in backup....

**Comment by cdjackson** [comment]
No - they are stored in the XML file, not the controller.
