### ISSUE TITLE
request to add  ZL7432 In-Wall Dual Relay Switch

### ISSUE THREAD

**Issue by rm65453** [cdjackson/HABmin#275]
here is the entry: http://www.pepper1.net/zwavedb/device/462

thank you.

**Comment by cdjackson** [comment]
Done.

**Comment by rm65453** [comment]
thanks @cdjackson trying to figure out a way to get this device to report its status to the zwave controller. doesnt seem like the option exists.

**Comment by cdjackson** [comment]
It looks like it has an association group for this purpose, so configure this to point to your controller.

**Comment by rm65453** [comment]
thanks for all your help.
