### ISSUE TITLE
Request to add D-Link DCH-Z110

### ISSUE THREAD

**Issue by Carolinger** [cdjackson/HABmin#283]
Manufacturer:264 [ID:e,Type:2]
http://products.z-wavealliance.org/products/1151
[D-Link DCH-Z110_120 manual.pdf](https://github.com/cdjackson/HABmin/files/33116/D-Link.DCH-Z110_120.manual.pdf)

**Comment by Carolinger** [comment]
From what I saw it should be identical to Philio PST-02 that is already in database. ;-)

**Comment by cdjackson** [comment]
Great - thanks. I’ll take a look at it in the next day or so.

**Comment by Carolinger** [comment]
Hi again. Thanks for the fast action. Just tried version from cloudbees. Strangely the device shows up now as "Remote Control" while actually it is a "Door Sensor"...

**Comment by cdjackson** [comment]
I misnamed it - I’ll fix this, but does it work ok?

**Comment by Carolinger** [comment]
I had just a quick look at it yesterday. I will check it as soon as I find time next days. (my first impression was that the configuration parameters also looked more like a remote but let me check first)
In any case I'll give the feedback!

**Comment by Carolinger** [comment]
Would be great if you could give me a short notice after you found the time to correct this so I can test directly. Please let me know if there is anything more I can help you with...
Currently I can't use my device because I need to change configuration in order to get the door-contact working with openHAB.
Greetings from Germany!

**Comment by cdjackson** [comment]
Hi,
Did we resolve this (I think so, but please can you confirm)?

Thanks
Chris

**Comment by jh1777** [comment]
Hi, 
I just set up openHab 1.8.1 with latest HABmin etc. but my Sensor DCH-Z110 ist still not recognized (see screenshot). It's my first Z-Wave device. Its running on a Pi2 - Z-Wave Stick is properly set up.

![habmin](https://cloud.githubusercontent.com/assets/17355971/13197224/461b516a-d7e7-11e5-9470-62afcc552f35.jpg)
Can anyone help?

**Comment by cdjackson** [comment]
Please update to a more recent version of the binding - this device is supported already.

Cheers
Chris

**Comment by jh1777** [comment]
I am using:
**org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar**

**Comment by cdjackson** [comment]
Yes, I saw that from the image you posted - it’s 6 months old (I think the date on the file in your image was August?

**Comment by jh1777** [comment]
Well I just downloaded it today. Can you give me a helpful link for a newer one? I saw a post by you saying that in 1.8 it's supported. And I have 1.8.0 so I thought it should work.

**Comment by cdjackson** [comment]
You have a 1.8 SNAPSHOT - not 1.8 as this was released in January… You can download the latest versions from the openhab pages, or if you want the really latest version (i.e. nightly snapshot) go here (https://openhab.ci.cloudbees.com/ <https://openhab.ci.cloudbees.com/>) and download the OH1 addons.

**Comment by jh1777** [comment]
https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastStableBuild/org.openhab.binding$org.openhab.binding.zwave
Just saw a 1.9.0 jar file there. That's what you mean, correct? 
Will that work with HABmin 1.7.0 or is that also an old one?

**Comment by cdjackson** [comment]
Yep - that’s the one… It will work fine with other versions of OH and HABmin…  Generally, the released versions of OH ae a release in time - they are tested, and should be good, but the nightly snapshot will always be more up to date - especially when it comes to zwave database - and there’s no incompatibility issue…

**Comment by jh1777** [comment]
Thanks for your unbelievable quick help, it's working now! 
Unfortunately I am still (after trying OH2 before) unable to get that BINARY_SENSOR to life, as well as the Temperature in °C but thats another problem...

**Comment by cdjackson** [comment]
I’d suggest if you’re having trouble, put a post on the openhab forum as someone there will have this device and should be able to help…

**Comment by cdjackson** [comment]
Very old ZWave issue - update database if not resolved.
