### ISSUE TITLE
Request to add  Z-Wave.Me Flush-Mountable Dimmer v1.8

### ISSUE THREAD

**Issue by yased** [cdjackson/HABmin#285]
Hi.

I didn't find this device in database. Add, please.
http://www.pepper1.net/zwavedb/device/273

ps it's XML file.

[zme_21000.pdf](https://github.com/cdjackson/HABmin/files/53623/zme_21000.pdf)

**Comment by yased** [comment]
Hi.

Will you add this device? Or I do something wrong?

**Comment by cdjackson** [comment]
Sorry - I missed this. Can you also provide the type and ID that HABmin lists - this is needed to update the products.xml file.

**Comment by yased** [comment]
Thanks for answer. ZWave.me[ID:2, Type:1000].

And please - watch in this thread: https://github.com/cdjackson/HABmin/issues/286

**Comment by yased** [comment]
Did you forget about me? =)

**Comment by cdjackson** [comment]
Sorry - last week was very busy and then I spent most of the weekend trying to sort out the OH2 problems with the zwave binding (without success).

I will add this tonight.

Do you actually have this working in OH - if so, can you supply the nodeX.xml file that OH produces?

**Comment by yased** [comment]
And this item work.
[node10.txt](https://github.com/cdjackson/HABmin/files/94000/node10.txt)

**Comment by yased** [comment]
Hi.

Thanks for adding. But it's not work correctly. I copied the new jar file from this link:
https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.zwave/target/
to Addons directory, restarted openhab and got some bugs. I made video from my desktop. Please, look up at this:
https://youtu.be/jfECXT9NbdU
What's wrong? Bug in jar built?

**Comment by cdjackson** [comment]
I suspect this is an issue I’ve (hopefully) just fixed, so please try tomorrows binding.

**Comment by yased** [comment]
I will test settings at this weekend. But at first glance it seems to work. Thank you for helping.

ps proplem with showing devices in database is still actually.

**Comment by yased** [comment]
Hi.

I tested dimmer yesterday. I tried to setup up settings. It's worked. But after I can't open settings again. I attached openhab log. Please, look at it.
[openhab.txt](https://github.com/cdjackson/HABmin/files/126134/openhab.txt)

**Comment by cdjackson** [comment]
Please try the latest version as there was a further update yesterday.

**Comment by yased** [comment]
Not work with last jar.

Last log:
2016-02-11 15:36:33.643 [WARN ] [.b.z.i.c.ZWaveConverterHandler] - No converter found for command class = NODE_NAMING, ignoring event.
2016-02-11 15:36:34.059 [ERROR] [.c.ZWaveNodeNamingCommandClass] - NODE 10 : Node Name report error in message length
2016-02-11 15:36:34.061 [INFO ] [.c.ZWaveNodeNamingCommandClass] - NODE 10: Node location: null
2016-02-11 15:36:34.062 [WARN ] [.b.z.i.c.ZWaveConverterHandler] - No converter found for command class = NODE_NAMING, ignoring event.
2016-02-11 15:36:34.500 [ERROR] [.z.i.c.ZWaveIndicatorConverter] - NODE 10: You must specify an Indicator bit for item = DimmerLight_big_room, ignoring event.
2016-02-11 15:36:34.961 [INFO ] [.c.ZWaveNodeNamingCommandClass] - NODE 10: Node name: 

Give you full log?

**Comment by cdjackson** [comment]
I think this is now a different issue. It seems that it now works, but you have an issue with configuration of the indicator class and no naming class? I'm not familiar with this class so it might be best to ask this question on the forum, but I don't think it's related to adding this device to the database. If the database is now added, I suggest we close this and raise a new issue if there's actually a problem with these other classes?

**Comment by yased** [comment]
Yes, you can close the issue. I think that it isn't error of database. Thank you!
