### ISSUE TITLE
Request to add Popp Battery Wall Controller

### ISSUE THREAD

**Issue by casperleenheer** [cdjackson/HABmin#289]
Hi,

I bought a POPP Battery Wall Controller. It's not recognized by Openhab and it's also not in the Pepper database. What can I do to get it added to the Zwave binding?

I found an xml for it in the OpenZwave forum. Maybe it is usefull:

[POP009303.txt](https://github.com/cdjackson/HABmin/files/86265/POP009303.txt)

I closed the issue on the  Openhab forum.

Cheers Casper

**Comment by cdjackson** [comment]
Hi Casper,
Can you please send me the XML created by openhab?  I will use this to test my new device database…

Chris

**Comment by casperleenheer** [comment]
Hi Chris,

That's a problem, it didn't. I added the log file. I hope it helps...

Cheers,

Casper
[zwave-2016-02.log.zip](https://github.com/cdjackson/HABmin/files/87661/zwave-2016-02.log.zip)

**Comment by cdjackson** [comment]
Did you mean to close this?

**Comment by casperleenheer** [comment]
No, I closed the issue I opened at the openhab forum. Please keep this open :-)

**Comment by cdjackson** [comment]
Ok - but you also closed this one - I guess accidentally?… Can you reopen it?

**Comment by casperleenheer** [comment]
I did... I'm a donkey.

**Comment by cdjackson** [comment]
Is this in the online database (www.cd-jackson.com)? If not then please add there - I'll close this, but if you need help adding to the database then let's discuss on the forum.

**Comment by casperleenheer** [comment]
Hi Chris,

No it's not there. I just didn't make the time to add it. I hope to get
some time in July.

Thanks,

Casper

Op wo 15 jun. 2016 om 08:28 schreef Chris Jackson <notifications@github.com

**Comment by cdjackson** [comment]
Thanks - if you have any questions, please let me know…

Chris

**Comment by prey87** [comment]
any update here?
I have two of these controllers, how can i help?

**Comment by cdjackson** [comment]
No update - this is closed. If you have problems with devices then please discuss on the forum as it's nothing to do with HABmin.
