### ISSUE TITLE
Request to add entry into database - : Fibaro System [ID:2000,Type:700]

### ISSUE THREAD

**Issue by bl0ckk** [cdjackson/HABmin#293]
Hi all..first off as a complete newbie to openhab/habmin I have to commend all involved.  It's been fantastic!!

I just purchased a Fibaro door/window sensor and I am receiving the following:

No database entry: Fibaro System [ID:2000,Type:700]

Is there anyway to have this device added?

Thanks so much!!

**Comment by cdjackson** [comment]
I’ve added it to the database - it should be available in tomorrows snapshot.

**Comment by bl0ckk** [comment]
Woohoo!! Thank you so much!!

**Comment by cdjackson** [comment]
No probs :)
