### ISSUE TITLE
Problem inserting my fibaro Door Opener (FGK-101)

### ISSUE THREAD

**Issue by pdandis** [cdjackson/HABmin#294]
Hi,

first of all I'm a new in this area. I installed openhab on a raspi PI, according apt-get and HABmin1.
I'm using a AEOTEC Gen5 Stick it seems all is fine. HABmin shows the stick a node1 Zwave USB controller, light is green.

 ------------Number of Nodes Found Registered to ZWave Controller-------
 - # Nodes = 1
------------------------------------------------------------------
So my next step was to insert the fibaro FGK-101 Door / Windows opener by tripple clicking. I have 3 ones but all inserting tries failed. Reset doesn't helped
 sudo /etc/init.d/openhab status -l shows at the end of the output:
Node 1: Neighbor update failed several times
and
Node 255: Timeout while sending message Requiring 2 attempts.

During startup the only error message ist software reset is false?

I'm no idea whats wrong? Any ideas what I can do?

Many thx in advance

Peter

**Comment by sihui62** [comment]
Maybe this is not the best place to ask questions, openhab has a forum for that:
[https://community.openhab.org/](https://community.openhab.org/)
But anyway, I also have this sensor and was able to include it by clicking the BACK button three times (not the button in the battery case).
Good luck.

**Comment by cdjackson** [comment]
Agreed - it#s probably best to discuss this on the forum. I know from personal experience that these sensors are not the easiest to include but they do work fine once you finally get it included.

**Comment by pdandis** [comment]
Hi,
thx for your hints, by the way the tried it with the BACK Button and the internal tmp button, same result ..
I will put my question in the openhab forum .

**Comment by cdjackson** [comment]
From my experience, getting this included was a pain. I tried many times and finally it worked, but it's not obvious why it didn't work the other times...

Good luck.
