### ISSUE TITLE
Request to add entry into database: Fibaro System [ID:1001,Type:801]

### ISSUE THREAD

**Issue by bompi75** [cdjackson/HABmin#300]
I just purchased a Fibaro FGMS-001 mulitisensor and I am receiving the following:

2016-03-06 13:02:48.398 [DEBUG] [.z.i.config.ZWaveConfiguration:276 ]- NODE 3: No database entry: Fibaro System [ID:1001,Type:801]

Is there anyway to have this device added? The device is listed in the "Product explorer"

Thanks sin advance!

**Comment by cdjackson** [comment]
I’ve updated the database - this should be in tomorrows build.

**Comment by bompi75** [comment]
Thanks a lot - i'm quite new to this, som my question is - must I do someting to get the update?

**Comment by cdjackson** [comment]
Yes - you’ll need to download the latest binding from cloudbees tomorrow 

https://openhab.ci.cloudbees.com/job/openHAB1-Addons/ <https://openhab.ci.cloudbees.com/job/openHAB1-Addons/>

**Comment by bompi75** [comment]
Thanks a lot!
Lars

Sent from Outlook Mobile




On Sun, Mar 6, 2016 at 4:36 AM -0800, "Chris Jackson" <notifications@github.com> wrote:










Yes - you’ll need to download the latest binding from cloudbees tomorrow 



https://openhab.ci.cloudbees.com/job/openHAB1-Addons/ <https://openhab.ci.cloudbees.com/job/openHAB1-Addons/>
