### ISSUE TITLE
Request to load devices: 406 Not Acceptable

### ISSUE THREAD

**Issue by JHK** [cdjackson/HABmin#307]
When loading the devices in the Z-Wave bindings tab of the habmin webinterface I get a 406. The devices are therefore not showed. Properties tab works though.

This is the request my browser sent to query the devices:
````curl -v 'http://homeautomation:8080/services/habmin/zwave/nodes/?_dc=1464942278181&domain=nodes%2F' -H 'Host: homeautomation:8080' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0' -H 'Accept: application/json' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --compressed -H 'Content-Type: application/json' -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: http://homeautomation:8080/habmin/' -H 'Cookie: ext-graphWindowSizer=o%3A; ext-configWindowSizer=o%3A' -H 'Connection: keep-alive'````

and it got the following answer:
````
* Connected to homeautomation (127.0.1.1) port 8080 (#0)
> GET /services/habmin/zwave/nodes/?_dc=1464942278181&domain=nodes%2F HTTP/1.1
> Accept-Encoding: deflate, gzip
> Host: homeautomation:8080
> User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
> Accept: application/json
> Accept-Language: de,en-US;q=0.7,en;q=0.3
> Content-Type: application/json
> X-Requested-With: XMLHttpRequest
> Referer: http://homeautomation:8080/habmin/
> Cookie: ext-graphWindowSizer=o%3A; ext-configWindowSizer=o%3A
> Connection: keep-alive
> 
< HTTP/1.1 406 Not Acceptable
< Date: Fri, 03 Jun 2016 08:26:06 GMT
< X-Atmosphere-first-request: true
< X-Atmosphere-tracking-id: 092bc161-60e1-42ed-b003-228ba208354e
< Content-Type: application/json
< Content-Length: 0
* Server Jetty(8.1.3.v20120522) is not blacklisted
< Server: Jetty(8.1.3.v20120522)
< 
* Connection #0 to host homeautomation left intact
````

In the openhab logs I could not find any error messages. I recently updated to openhab 1.8.3, but haven't used the devices view in the admin for a while. So it might also be unrelated to that particular update.

**Comment by cdjackson** [comment]
Why are you making requests using curl? It looks like the node id is malformed.

domain=nodes%2F

**Comment by JHK** [comment]
Just copied the request from the browser using the developer tools.
Am 03.06.2016 1:21 nachm. schrieb "Chris Jackson" <notifications@github.com

**Comment by JHK** [comment]
Ah damn. It was that `-Dgnu.io.rxtx.SerialPorts=/dev/ttyAMA0` to JAVA_ARGS_DEFAULT thingy, which was removed by the package upgrade. Sorry for the inconvenience.

**Comment by cdjackson** [comment]
No probs - at least it's working...
