### ISSUE TITLE
Sitemap configuration redesign idea

### ISSUE THREAD

**Issue by mishoboss** [cdjackson/HABmin#31]
My proposal is that Widgets panel become more like a toolbox panel, i.e. a lot thinner and only icons. On hover, show bubble with widget name. Then place the Properties panel below the Sitemap tree panel and place the Widgets panel (toolbox) in left of both. I made a simple sketch of this idea:
![habmin](https://f.cloud.github.com/assets/1629929/1189894/ad9f2d10-2426-11e3-9dbd-c91b47c6a865.png)

I think this approach will both save some space for bigger Sitemap Configuration panel and it's more logical, because it mimics most of the IDEs.

**Comment by cdjackson** [comment]
Will not be implemented in OH1
