### ISSUE TITLE
D-Link DCH-Z510 not identified

### ISSUE THREAD

**Issue by m4rquez** [cdjackson/HABmin#310]
Hi Chris,

i just bought an DCH-Z510, which is in the Database.
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/330

I'm not sure, but i think it's not identified correctly in Habmin, maybe the Version is responible for this.
_2016-07-22 15:51:13.163 [ERROR] [.z.i.config.ZWaveConfiguration] - NODE 4: Error in doSet - no database found_
![screenshot 2016-07-22 15 42 17](https://cloud.githubusercontent.com/assets/20598399/17058928/f308561c-5022-11e6-8f66-e30a1418e160.png)

I also have some issues controlling the siren.
Tried the following Items:
Switch SIREN {zwave="4:command=BASIC"} (ON: starts playing, OFF: nothing happens)

I think DCH-Z510 is the same devive as Zipato PSE02, in its manual i found the following:
_The device supports using SWITCH_MULTILEVEL SET to play the
sound. The sound ID is defined as follows:
1 or 255: Emergency sound.
2: Fire alert.
3: Ambulance sound.
4: Police car sound.
5: Door chime.
6~99: Beep Beep.
0: means stop the sound._

So i tried:
Dimmer SIREN_SOUND {zwave="4:command=SWITCH_BINARY"}
and used a slider in the sitemap, which assigns values between 0 and 100, but i always get 
_2016-07-22 15:16:30.462 [WARN ] [i.c.ZWaveBinarySwitchConverter] - NODE 4: No converter found for item = SIREN_SOUND, endpoint = 0, ignoring command._

Hope you can help, i'm a z-wave beginner...

**Comment by cdjackson** [comment]
Yep - it’s not in the OH1 binding. I’ll add it tonight.

> The device supports using SWITCH_MULTILEVEL SET to play theDimmer SIREN_SOUND {zwave="4:command=SWITCH_BINARY”}
...
> So i tried:
> Dimmer SIREN_SOUND {zwave="4:command=SWITCH_BINARY"}


Shouldn’t this read SWITCH_MULTILEVEL?

**Comment by m4rquez** [comment]
tried this before, but then i get:

2016-07-22 17:54:30.014 [WARN ] [.b.z.i.c.ZWaveConverterHandler] - No command class found for item = SIREN_SOUND, command class name = switch_multilevel, ignoring execute refresh.

ist this due to the missing db entry?

**Comment by cdjackson** [comment]
No - it won’t be related to the database. It likely means the device is not reporting this command class. I’d need to check the database to see if we have a workaround for this device to add the unknown class.

**Comment by m4rquez** [comment]
Hi Chris,

thanks, now i'm getting some understanding of z-wave.

I still can't turn off the sound, can you tell me what i'm doing wrong?

Using a switch item:
_Switch SIREN {zwave="4:command=SWITCH_BINARY"}_

Manual says: 
_Using the SWITCH_BINARY_SET to play the siren, 0xFF will play the emergency sound, 0x00 will stop to play._

**Comment by cdjackson** [comment]
I’m not sure - this should send 0xFF and 0x00 with this item. I would suggest grabbing a debug log (check out the OH1 ZWave wiki on how to do this) and then play it back using the online viewer on my website (cd-jackson.com). If the binding is sending the correct stuff, then I’m not sure where to go next - if not, we can take a better look at the binding.

**Comment by m4rquez** [comment]
looks good to me?! but it doesn't stop playing the emergency sound.


Logfile: [zwave.txt](https://github.com/cdjackson/HABmin/files/380307/zwave.txt)

![screenshot 2016-07-24 16 52 27](https://cloud.githubusercontent.com/assets/20598399/17084482/3813827a-51bf-11e6-95ba-c117addd08bc.png)

**Comment by cdjackson** [comment]
Sorry - not really sure I can help. I had a look in the manual and can’t see anything more than you already know.

I’d suggest starting a thread on the OH forum as there are a few people using this device so hopefully someone will be able to help.

**Comment by m4rquez** [comment]
ok, thanks anyway!

you added the device in the OH1 binding?
do i have to update the jar manually?

**Comment by cdjackson** [comment]
Yes, it was added a couple of days back -:
https://github.com/openhab/openhab/pull/4553 <https://github.com/openhab/openhab/pull/4553>

You will need to grab the latest version from cloudbees and copy into the addons folder...

**Comment by m4rquez** [comment]
ok, just for completeness. i tried a new one, and had no problems playing and stopping the sound!

@chris: any idea for the not reported SWITCH_MULTILEVEL?

**Comment by cdjackson** [comment]
I can't find any reference to the multilevel switch in the device - it doesn't mention it in the manual. Is there anything to confirm it's supported? I also see no mention of it in the OZW database, and I also checked that it's not a mandatory command class for the device class. I also checked the Zipato PSE02 manual and it also doesn't list it as a supported command class.

Based on the evidence, I can't see that it's supported?

**Comment by m4rquez** [comment]
Hi Chris, got this Information from the Zipato Manual, i thought this schould also be the same device. 

[ZIPATO-PSE02.pdf](https://github.com/cdjackson/HABmin/files/390900/ZIPATO-PSE02.pdf)

I have no idea how to change the sound otherwise.

**Comment by cdjackson** [comment]
I see what you mean - the previous PSE02 manual I found never mentioned this. What’s strange is that this command class isn’t listed in the supported command classes even in this manual!

**Comment by m4rquez** [comment]
I was wondering about that too.

Is there a simple way to test if the device accepts the undocumented/unreported command class?

**Comment by cdjackson** [comment]
Ok, some further investigation shows that this isn’t supported. It will only work if you have the alarm securely included, which isn’t currently working in OH at the moment. I expect that it would report the multilevel switch class in the secure supported classes, but that at least explains the problem.

Sorry…

**Comment by cdjackson** [comment]
So I'll close this now since the device is supported to the max possible at this time. Any problems, please reopen or open another issue.
