### ISSUE TITLE
VIS-ZD-2102

### ISSUE THREAD

**Issue by m4rquez** [cdjackson/HABmin#311]
Hi,

i'm using a VIS-ZD-2102 door/window sensor.
It is working as it should. Reports its battery level several times per day, reports every open/close.

Nevertheless, i'm getting warnings and errors in the zwave log like:
**_2016-08-05 21:22:37.287 [WARN ] [i.p.s.IsFailedNodeMessageClass:53  ]- NODE 3: Is currently marked as failed by the controller!_**
after some messages being dropped.
**_2016-08-05 21:30:12.896 [ERROR] [WaveController$ZWaveSendThread:1347]- NODE 3: Timeout while sending message. Requeueing - 2 attempts left!_**

It is the only node with this behavior, another battery driven device is never marked as failed by the controller.

Is this a configuration or maybe a database failure? The controller should know, that a battery device isn't always responding?

**Comment by cdjackson** [comment]
This information comes from the controller only - it's nothing to do with the database. Normally the controller will never put a battery device into the failed list so I don't know why this would be the case here...

Please ask questions on the openhab community forum rather than here :)
