### ISSUE TITLE
Add new product: Cyrus 4-in-1 multisensor

### ISSUE THREAD

**Issue by aplachy** [cdjackson/HABmin#312]
Hi!

As I didn't got any response in the openhab issus group, I post my request here again and hope to get a response:

I have tried to add a Cyrus "4-in-1 Multisensor" to my openhab/habmin configuration, but it seems that this sensor is not in the product database since I got this debug info:

NODE 27: "No database entry: Vision Security" [ID:2101,Type:2021]

I have found the description of the device and zwave command classes online - but only in german - sorry...
http://www.cyrus-technology.de/fileadmin/data/userdownloads/ZWave4in1MS/4-in-1_Multisensor_Z-Wave_manual_DE.pdf

Openhab has generated this xml file for this device, but I could not set any properties in habmin:

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>GARAGE_DOOR</genericDeviceClass>
    <specificDeviceClass>SIMPLE_GARAGE_DOOR</specificDeviceClass>
  </deviceClass>
  <homeId>0xe8433edc</homeId>
  <nodeId>27</nodeId>
  <version>4</version>
  <manufacturer>0x109</manufacturer>
  <deviceId>0x2101</deviceId>
  <deviceType>0x2021</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2016-11-23T05:39:08+0000</healState>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <nodeInformationFrame/>
  <supportedCommandClasses>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <batteryLevel>70</batteryLevel>
        <batteryLow>false</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>SENSOR_MULTILEVEL</commandClass>
      <multiLevelSensorCommandClass>
        <version>5</version>
        <instances>1</instances>
        <sensors>
          <entry>
            <multilevelSensorType>LUMINANCE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>LUMINANCE</sensorType>
              <initialised>false</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>TEMPERATURE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>TEMPERATURE</sensorType>
              <initialised>false</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>RELATIVE_HUMIDITY</multilevelSensorType>
            <multilevelSensor>
              <sensorType>RELATIVE_HUMIDITY</sensorType>
              <initialised>false</initialised>
            </multilevelSensor>
          </entry>
        </sensors>
        <isGetSupported>true</isGetSupported>
      </multiLevelSensorCommandClass>
    </entry>
    <entry>
      <commandClass>ALARM</commandClass>
      <alarmCommandClass>
        <version>1</version>
        <instances>1</instances>
        <alarms/>
        <isGetSupported>true</isGetSupported>
      </alarmCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>1</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <targetNodeId>1</targetNodeId>
        <interval>3600</interval>
        <minInterval>600</minInterval>
        <maxInterval>604800</maxInterval>
        <defaultInterval>3600</defaultInterval>
        <intervalStep>600</intervalStep>
        <lastWakeup>2016-11-23 05:39:08.214 UTC</lastWakeup>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>5.1</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>12</int>
  </nodeNeighbors>
  <lastSent>2016-11-23 05:39:08.221 UTC</lastSent>
  <lastReceived>2016-11-23 05:39:08.214 UTC</lastReceived>

Could you please add this device to the database?
If needed I could post more infos...

How could the new update could be installed?
At the moment I have the z-wave binding version 1.8.3 with habmin 0.1.4 installed on openhab 1 default debian system (fresh installed a few weeks ago).

Thanks!
Andreas

![4-in-1-multisensor-habmin](https://cloud.githubusercontent.com/assets/19152094/20572836/7572b8c2-b1ad-11e6-9953-7bf4fab45878.JPG)

**Comment by cdjackson** [comment]
This appears to be this device looking at the ids -:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/307 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/307>

Can you confirm?

**Comment by aplachy** [comment]
Hey yeah thats the product.

How could I setup this device in my environment?

Thank you,
Andreas

**Comment by aplachy** [comment]
I just updated the zwave binding jar file and restarted openhab.
My sensor is now working as expected.

Thank you again for helping!

**Comment by maikbooehme** [comment]
Hello Andreas,
could you please let me know, where and how you updated the jar file ?
Where did you got it ?

Best regards
Maik

**Comment by cdjackson** [comment]
I suggest to discuss on the openhab forum - community.openhab.org
