### ISSUE TITLE
No Products in Product Explorer

### ISSUE THREAD

**Issue by RaimondB** [cdjackson/HABmin#313]
Because of a new Z-Wave Device I bought, 2x Switch 2 from Fibaro (FGS-223) I wanted to get the latest Zwave database because I saw a commit was in there for this device.

I am using a Raspberry Pi.

I installed 1.8.3 zwave binding via apt-get and removed the 1.8.0.xxx binding I think i got with habmin.
I had to manually remove the 1.8.0.xxx version because both where listed.

However, now I don't see any products in the product explorer anymore. Any ideas how to fix this?

Thanx,
Raimond

**Comment by cdjackson** [comment]
V1.8.3 has a broken database - please update to a the latest version and it should work.

**Comment by RaimondB** [comment]
Could you please elaborate or point me to directions to get the latest version? Currently I am using apt-get and it seems 1.8.3 is the latest version..

**Comment by cdjackson** [comment]
1.9.0 is the latest snapshot - it’s available on cloudbees https://openhab.ci.cloudbees.com
