### ISSUE TITLE
symbol lookup error after zwave configuration

### ISSUE THREAD

**Issue by DevUrandomFoo** [cdjackson/HABmin#316]
Hi,

after setup the zwave stick in openhab 2 beta 4 my openhab crashed with the following error:

/usr/bin/java: symbol lookup error: /root/openHAB2/userdata/tmp/libNRJavaSerial_HF_root_0/libNRJavaSerial_HF.so: undefined symbol: __fdelt_chk

What I did:
- install openhab default (just unzip)
- start it (start.sh)
- select basic ui (expert ui with same problem)
- install zwave addon / binding
- add thing and configure the correct device ( /dev/ACM0 )
- get error -1 when press save/add
- see error on shell, openhab process died

Before I run openhab 1.8.2 with org.openhab.io.habmin-1.7.0-SNAPSHOT.jar and org.openhab.binding.zwave-1.8.2.jar on the same raspberry with zwave and no problems.

I use a Z-Wave ZME_UZB1 Stick
BR,
Manuel

**Comment by cdjackson** [comment]
Hi.
This isn't really anything to do with HABmin. I'd suggest raising a question on the [OH forum](community.openhab.org) - there have been some changes recently with the serial driver - the forum is the best place to discuss this though.

Cheers
Chris
