### ISSUE TITLE
Initialization problem with Fibaro Door Sensor FGK101

### ISSUE THREAD

**Issue by groobie81** [cdjackson/HABmin#317]
Hi

I have troubles with the initlization of my Fibaro Door Sensor FGK101. Node shows up in openHab 2 PaperUI. But no events or data is received by the not

I attached the log file and some screen shots:
![openhab_screenshot2](https://cloud.githubusercontent.com/assets/25547769/22618130/640c54d8-ead5-11e6-9fdc-e53f816e011f.PNG)
![openhab_screenshot1](https://cloud.githubusercontent.com/assets/25547769/22618131/640d5248-ead5-11e6-87f9-1babafcb590c.PNG)

Logs:
[openhablog.txt](https://github.com/cdjackson/HABmin/files/752236/openhablog.txt)

Some help would be much appreciated.

Many thanks,
Oliver

**Comment by cdjackson** [comment]
Please discuss support issues on the openhab community forum
