### ISSUE TITLE
MessageBodyWriter not found for media type=text/plain

### ISSUE THREAD

**Issue by 5iver** [cdjackson/HABmin#323]
Discussion here: https://community.openhab.org/t/error-entry-by-habmin-messagebodywriter-not-found-for-media-type-text-plain/44190

This occurs for all Things, not just zwave. I assume it is something to do with i18n. My laptop is using Firefox on Fedora27, and my locale in OH is set to United States/English. I have also seen the same with Chrome on Windows 10.

![screenshot from 2018-06-03 12-31-54](https://user-images.githubusercontent.com/21967853/40888782-554a0eb8-672a-11e8-989d-715c41caccab.jpg)

![screenshot from 2018-06-03 12-32-19](https://user-images.githubusercontent.com/21967853/40888780-4ebb84fa-672a-11e8-8365-56c84b0e8d21.jpg)

![screenshot from 2018-06-03 12-31-03](https://user-images.githubusercontent.com/21967853/40888786-63696e08-672a-11e8-8a39-9b1e4cd3e148.jpg)

![screenshot from 2018-06-03 12-31-23](https://user-images.githubusercontent.com/21967853/40888785-5d4ce428-672a-11e8-8d77-796ffb466003.jpg)
```
{"error":{"message":"HTTP 500 Internal Server Error","http-code":500,"exception":{"class":"javax.ws.rs.InternalServerErrorException","message":"HTTP 500 Internal Server Error","localized-message":"HTTP 500 Internal Server Error","cause":"org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException"}}}
```

**Comment by cdjackson** [comment]
For the channel errors this looks like what I said on the forum. HABmin is requesting configuration information for channels that have no configuration, and the server is returning an error. I've no idea what the error actually means.

I recall in the past we had a similar issue with configuration on things - if a thing didn't have any configuration, then you got an error. I changed it for things - I suspect it should be changed for everything. I don't think this is an issue in HABmin...

The last one just looks like it's requesting the config status - this looks fine. The REST call takes no parameters other than the thing UID, so I don't think this is an issue with HABmin either.
![image](https://user-images.githubusercontent.com/1041475/40889463-2205c576-675f-11e8-85ff-7feb98837d14.png)

**Comment by cdjackson** [comment]
This is the other issue I was thinking of -:
https://github.com/eclipse/smarthome/pull/1268

**Comment by cdjackson** [comment]
@openhab-5iver I don't think there's a lot I can do about this. I could not request the config descriptions for channels, but that would cause other problems. I don't think there's a way to get the channel config without requesting it, and if it doesn't exist, then we have 404.

The status error I can't replicate here - I don't see any issue with the URI that HABmin is sending, so I think this is an ESH problem? It might be a ZWave binding problem - although you said above it's not ZWave specific, so I guess it's ESH...

**Comment by 5iver** [comment]
> The status error I can't replicate here

That's strange... I can replicate the same error (in the log) and the 500 using REST-DOCS, so would think you would get the same. Another reason why I was thinking it was somehow related to i18n. But now thinking about it, it's got to just be a REST API issue.

![screenshot from 2018-06-03 16-08-13](https://user-images.githubusercontent.com/21967853/40890724-825dd768-6748-11e8-83d8-d3a551adb5a9.jpg)

**Comment by cdjackson** [comment]
Nope - I can’t seem to replicate it on my production system at least - it’s a couple of months old.

Either way, I don’t think this is a HABmin issue - if you’re replicating it in the REST interface, then it’s not HABmin…

**Comment by 5iver** [comment]
Agreed. And BTW, it is the 500 error that causes the 
```
2018-06-03 16:28:58.816 [ERROR] [.jersey.message.internal.WriterInterceptorExecutor] - MessageBodyWriter not found for media type=text/plain, type=class java.util.Collections$UnmodifiableCollection, genericType=class java.util.Collections$UnmodifiableCollection.
```
I'll open an ESH issue for it.
