### ISSUE TITLE
Where are the XML?

### ISSUE THREAD

**Issue by casperleenheer** [cdjackson/HABmin#65]
Hi Chris,

I have setup a UDOO ARM based Debian server with an Aeon Stick. I got HABmin working, but I need to add the configuration to my two nodes. I can't see where the xml goes when I click on the save node button. I'm a big noob...

Thanks,

Casper

**Comment by steam73** [comment]
I know this is an old thread, but I have some zwave devices that are not known by habmin either. Can you still provide some help there? It's the greenwave ns310, which currently shows up as a 210, a comet zwave radiator thermostat, and some other stuff from horstmann that I dont know the numbers from right now, as I am reading up at my vacation addres.
I did see a xml file of the 310 on github, but I do not know what to do with it.

**Comment by cdjackson** [comment]
Hi,
I guess I also just sent you a reply on a separate topic :)

I’d suggest asking questions on the openhab forum since more people check there and will be able to help (including myself).

Chris
