### ISSUE TITLE
Login problem on HABmin start

### ISSUE THREAD

**Issue by devTechi** [cdjackson/HABmin#67]
When calling the HABmin webinterface the login form for the username and password keeps popping up all the time.
Using an android mobile chrome browser it is nearly impossible to get through to the webinterface. On a linux chromium you can achieve that, but you can see the form realoading, too.

**Comment by jongmana** [comment]
Unfortunately I'm too, am stuck with this problem.
Installed OpenHab 1.7.1, and as the Habmin 2 wiki describes I downloaded and unzipped the old Habmin 1.3 in the webapps folder, before I downloaded and unzipped the Habmin2 release on top of it.
Accessing the OH website works fine, but when I open the Habmin site I keep getting the login popup.
